import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{Baby,Users,Plus,Copy,RefreshCw,MessageCircle,ArrowLeft}from'lucide-react';
import'./style.css';
import'./admin-panel.css';
const API=(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'')+'/functions/v1/invite-api';
const APP_URL='https://cha-oliver-mvp.vercel.app/';
async function api(payload){if(!import.meta.env.VITE_SUPABASE_URL)throw new Error('Supabase não configurado');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro');return d}
const newPin=()=>String(Math.floor(1000+Math.random()*9000));
function AdminPanel(){
 const[code,setCode]=useState(sessionStorage.getItem('oliverAdmin')||''),[families,setFamilies]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[filter,setFilter]=useState(''),[showAdd,setShowAdd]=useState(false);
 const[displayName,setDisplayName]=useState(''),[groupName,setGroupName]=useState(''),[guestText,setGuestText]=useState(''),[saving,setSaving]=useState(false);
 const load=async(adminCode=code)=>{setLoading(true);setError('');try{const d=await api({action:'adminList',adminCode});setFamilies(d.families||[]);sessionStorage.setItem('oliverAdmin',adminCode)}catch{setError('Código administrativo inválido ou não foi possível carregar o painel.')}finally{setLoading(false)}};
 useEffect(()=>{if(code&&sessionStorage.getItem('oliverAdmin'))load(code)},[]);
 const resetToken=async f=>{if(!confirm(`Gerar um novo token para ${f.display_name}? O token anterior deixará de funcionar.`))return;const pin=newPin();try{await api({action:'adminSetPin',adminCode:code,familyId:f.id,pin});setFamilies(v=>v.map(x=>x.id===f.id?{...x,invite_pin_plain:pin}:x))}catch{setError('Não foi possível resetar o token.')}};
 const addFamily=async()=>{const guests=guestText.split(/\n|,/).map(x=>x.trim()).filter(Boolean);if(!displayName.trim()||!guests.length){setError('Informe o nome do núcleo e pelo menos um convidado.');return}setSaving(true);setError('');try{await api({action:'adminCreateFamily',adminCode:code,displayName:displayName.trim(),groupName:groupName.trim(),guests,pin:newPin()});setDisplayName('');setGroupName('');setGuestText('');setShowAdd(false);await load(code)}catch{setError('Não foi possível adicionar o novo núcleo.')}finally{setSaving(false)}};
 const message=f=>`Olá, ${f.display_name}! 💛\n\nEstamos preparando com muito carinho o Chá do Oliver e queremos celebrar esse momento com vocês.\n\nAcesse o convite:\n${APP_URL}\n\nPara confirmar a presença, procure pelo nome de um dos integrantes da família e utilize o código de acesso:\n${f.invite_pin_plain||'[gere o token no painel]'}\n\n📅 04 de dezembro (sexta-feira)\n🕕 Das 18h às 22h\n📍 Salão Terra Mágica\n\nTraga o amor, o sorriso e a fralda: estamos em contagem regressiva. 💛`;
 const copy=async f=>{await navigator.clipboard.writeText(message(f));alert('Texto do convite copiado!')};
 const whatsapp=f=>window.open('https://wa.me/?text='+encodeURIComponent(message(f)),'_blank','noopener,noreferrer');
 const shown=families.filter(f=>!filter||String(f.number||'').includes(filter)||f.display_name.toLowerCase().includes(filter.toLowerCase())||(f.guests||[]).some(g=>g.name.toLowerCase().includes(filter.toLowerCase())));
 if(!families.length)return <div className="adminPage"><div className="adminLogin"><Baby/><h1>Painel do Chá do Oliver</h1><p>Acesso reservado aos organizadores.</p><input type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Código administrativo" onKeyDown={e=>e.key==='Enter'&&load()}/><button className="primary" onClick={()=>load()} disabled={!code||loading}>{loading?'Entrando...':'Acessar painel'}</button>{error&&<div className="error">{error}</div>}<a href="/"><ArrowLeft/> Voltar ao convite</a></div></div>;
 return <div className="adminPage"><div className="adminWrap"><div className="adminHeading"><div><span className="eyebrow">CHÁ DO OLIVER</span><h1>Gerenciador de convidados</h1><p>{families.length} núcleos · {families.reduce((n,f)=>n+(f.guests?.length||0),0)} convidados cadastrados</p></div><div className="adminTopActions"><button className="primary" onClick={()=>setShowAdd(v=>!v)}><Plus/> Novo convidado</button><a href="/">Ver convite</a><button onClick={()=>{sessionStorage.removeItem('oliverAdmin');setFamilies([]);setCode('')}}>Sair</button></div></div>
 {showAdd&&<section className="adminAdd"><div><span className="eyebrow">NOVO NÚCLEO</span><h2>Adicionar convidados</h2><p>Cadastre a família e os integrantes. Um token de 4 dígitos será criado automaticamente.</p></div><div className="adminForm"><label>Nome do núcleo<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Ex.: Família Silva"/></label><label>Grupo <input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Ex.: Amigos, Família Gustavo..."/></label><label className="full">Convidados<textarea value={guestText} onChange={e=>setGuestText(e.target.value)} placeholder={'Um nome por linha\nGustavo\nVanessa'}/></label><div className="full formActions"><button onClick={()=>setShowAdd(false)}>Cancelar</button><button className="primary" onClick={addFamily} disabled={saving}>{saving?'Adicionando...':'Adicionar núcleo'}</button></div></div></section>}
 {error&&<div className="error adminError">{error}</div>}<div className="adminTools"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar número, núcleo ou convidado"/><span>{shown.length} resultado(s)</span></div>
 <div className="guestList">{shown.map((f,i)=><article className="guestRow" key={f.id}><div className="guestNumber">#{String(f.number||i+1).padStart(2,'0')}</div><div className="guestMain"><div className="guestTitle"><h3>{f.display_name}</h3><span className={'status '+(f.invite_status||'')}>{f.invite_status==='confirmed'?'Confirmado':f.invite_status==='declined'?'Não irá':f.invite_status==='partial'?'Parcial':'Aguardando'}</span></div><p>{(f.guests||[]).map(g=>g.name).join(' · ')}</p><div className="guestMeta"><span>Token: <b>{f.invite_pin_plain||'— — — —'}</b></span>{f.group_name&&<span>{f.group_name}</span>}</div></div><div className="guestActions"><button onClick={()=>resetToken(f)}><RefreshCw/> Resetar token</button><button onClick={()=>copy(f)} disabled={!f.invite_pin_plain}><Copy/> Copiar convite</button><button className="primary" onClick={()=>whatsapp(f)} disabled={!f.invite_pin_plain}><MessageCircle/> WhatsApp</button></div></article>)}</div></div></div>;
}
createRoot(document.getElementById('root')).render(<AdminPanel/>);