import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{Baby,Users,Plus,Copy,RefreshCw,MessageCircle,ArrowLeft,Pencil,Gift,CheckCircle2,Clock3,XCircle,Mail}from'lucide-react';
import'./style.css';
import'./admin-panel.css';
import'./admin-panel-fonts.css';
const API=(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'')+'/functions/v1/invite-api';
const APP_URL='https://cha-oliver-mvp.vercel.app/';
async function api(payload){if(!import.meta.env.VITE_SUPABASE_URL)throw new Error('Supabase não configurado');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro');return d}
const newPin=()=>String(Math.floor(1000+Math.random()*9000));
function AdminPanel(){
 const[code,setCode]=useState(sessionStorage.getItem('oliverAdmin')||''),[families,setFamilies]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[filter,setFilter]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[showAdd,setShowAdd]=useState(false),[editing,setEditing]=useState(null);
 const[displayName,setDisplayName]=useState(''),[groupName,setGroupName]=useState(''),[guestText,setGuestText]=useState(''),[saving,setSaving]=useState(false);
 const load=async(adminCode=code)=>{setLoading(true);setError('');try{const d=await api({action:'adminList',adminCode});setFamilies(d.families||[]);sessionStorage.setItem('oliverAdmin',adminCode)}catch{setError('Código administrativo inválido ou não foi possível carregar o painel.')}finally{setLoading(false)}};
 useEffect(()=>{if(code&&sessionStorage.getItem('oliverAdmin'))load(code)},[]);
 const resetToken=async f=>{if(!confirm(`Gerar um novo token para ${f.display_name}? O token anterior deixará de funcionar.`))return;const pin=newPin();try{await api({action:'adminSetPin',adminCode:code,familyId:f.id,pin});setFamilies(v=>v.map(x=>x.id===f.id?{...x,invite_pin_plain:pin}:x))}catch{setError('Não foi possível resetar o token.')}};
 const addFamily=async()=>{const guests=guestText.split(/\n|,/).map(x=>x.trim()).filter(Boolean);if(!displayName.trim()||!guests.length){setError('Informe o nome do núcleo e pelo menos um convidado.');return}setSaving(true);setError('');try{await api({action:'adminCreateFamily',adminCode:code,displayName:displayName.trim(),groupName:groupName.trim(),guests,pin:newPin()});setDisplayName('');setGroupName('');setGuestText('');setShowAdd(false);await load(code)}catch{setError('Não foi possível adicionar o novo núcleo.')}finally{setSaving(false)}};
 const beginEdit=f=>{setEditing({id:f.id,displayName:f.display_name,groupName:f.group_name||'',guests:(f.guests||[]).map(g=>({id:g.id,name:g.name}))});setShowAdd(false);window.scrollTo({top:0,behavior:'smooth'})};
 const saveEdit=async()=>{if(!editing.displayName.trim()||!editing.guests.some(g=>g.name.trim())){setError('O núcleo precisa ter nome e pelo menos um convidado.');return}setSaving(true);setError('');try{await api({action:'adminUpdateFamily',adminCode:code,familyId:editing.id,displayName:editing.displayName.trim(),groupName:editing.groupName.trim(),guests:editing.guests.filter(g=>g.name.trim())});setEditing(null);await load(code)}catch{setError('Não foi possível editar o núcleo.')}finally{setSaving(false)}};
 const message=f=>`Olá, ${f.display_name}! 💛\n\nEstamos preparando com muito carinho o Chá do Oliver e queremos celebrar esse momento com vocês.\n\nAcesse o convite:\n${APP_URL}\n\nPara confirmar a presença, procure pelo nome de um dos integrantes da família e utilize o código de acesso:\n${f.invite_pin_plain||'[gere o token no painel]'}\n\n📅 04 de dezembro (sexta-feira)\n🕕 Das 18h às 22h\n📍 Salão Terra Mágica\n\nTraga o amor, o sorriso e a fralda: estamos em contagem regressiva. 💛`;
 const copy=async f=>{await navigator.clipboard.writeText(message(f));alert('Texto do convite copiado!')};
 const whatsapp=f=>window.open('https://wa.me/?text='+encodeURIComponent(message(f)),'_blank','noopener,noreferrer');
 const familyMatchesStatus=f=>{if(statusFilter==='all')return true;if(statusFilter==='confirmed')return f.invite_status==='confirmed';if(statusFilter==='pending')return !f.invite_status||['invited','waiting'].includes(f.invite_status);if(statusFilter==='declined')return f.invite_status==='declined';if(statusFilter==='partial')return f.invite_status==='partial';return true};
 const shown=families.filter(f=>familyMatchesStatus(f)&&(!filter||String(f.number||'').includes(filter)||f.display_name.toLowerCase().includes(filter.toLowerCase())||(f.guests||[]).some(g=>g.name.toLowerCase().includes(filter.toLowerCase()))));
 const stats=useMemo(()=>{const guests=families.flatMap(f=>f.guests||[]),confirmed=guests.filter(g=>g.attendance==='yes').length,declined=guests.filter(g=>g.attendance==='no').length,pending=guests.length-confirmed-declined,diapers=families.flatMap(f=>f.diapers||[]),sizes={P:0,M:0,G:0,XG:0};diapers.forEach(d=>{if(sizes[d.diaper_size]!==undefined)sizes[d.diaper_size]++});return{invites:families.length,total:guests.length,confirmed,declined,pending,diapers:diapers.length,mimos:diapers.length,sizes}},[families]);
 const statusCounts=useMemo(()=>({all:families.length,confirmed:families.filter(f=>f.invite_status==='confirmed').length,pending:families.filter(f=>!f.invite_status||['invited','waiting'].includes(f.invite_status)).length,partial:families.filter(f=>f.invite_status==='partial').length,declined:families.filter(f=>f.invite_status==='declined').length}),[families]);
 if(!families.length)return <div className="adminPage"><div className="adminLogin"><Baby/><h1>Painel do Chá do Oliver</h1><p>Acesso reservado aos organizadores.</p><input type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Código administrativo" onKeyDown={e=>e.key==='Enter'&&load()}/><button className="primary" onClick={()=>load()} disabled={!code||loading}>{loading?'Entrando...':'Acessar painel'}</button>{error&&<div className="error">{error}</div>}<a href="/"><ArrowLeft/> Voltar ao convite</a></div></div>;
 return <div className="adminPage"><header className="adminSiteHeader"><a className="brand" href="/">Chá do Oliver</a><nav><a href="/">Início</a><a href="/#confirmar">Confirmar</a><a href="/#presente">Presentes</a><a href="/#local">Local</a><a className="adminNav active" href="/?painel=1">Painel</a></nav></header><div className="adminWrap"><div className="adminHeading"><div><span className="eyebrow">CHÁ DO OLIVER</span><h1>Gerenciador de convidados</h1><p>Acompanhe convites, confirmações e sugestões de presentes.</p></div></div>
 <section className="dashboard"><div className="statCard"><Mail/><span>CONVITES</span><strong>{stats.invites}</strong><small>núcleos familiares</small></div><div className="statCard"><Users/><span>CONVIDADOS</span><strong>{stats.total}</strong><small>pessoas cadastradas</small></div><div className="statCard success"><CheckCircle2/><span>CONFIRMADOS</span><strong>{stats.confirmed}</strong><small>presenças confirmadas</small></div><div className="statCard pending"><Clock3/><span>A CONFIRMAR</span><strong>{stats.pending}</strong><small>aguardando resposta</small></div><div className="statCard declined"><XCircle/><span>RECUSADOS</span><strong>{stats.declined}</strong><small>não irão</small></div></section>
 <section className="giftDashboard"><div className="giftSummary"><div className="giftSummaryIcon"><Gift/></div><div><span className="eyebrow">CONTROLE DE PRESENTES</span><h2>Sugestões esperadas</h2><p>Baseado nas confirmações e na modalidade de presente escolhida por cada núcleo.</p></div></div><div className="giftNumbers"><div><strong>{stats.diapers}</strong><span>pacotes de fraldas</span></div><div><strong>{stats.mimos}</strong><span>mimos esperados</span></div></div><div className="diaperSizes">{Object.entries(stats.sizes).map(([s,n])=><div key={s}><b>{s}</b><strong>{n}</strong><span>pacote{n===1?'':'s'}</span></div>)}</div></section>
 <section className="adminManagerBar"><div><span className="eyebrow">GERENCIADOR DE CONVIDADOS</span><h2>Convites e núcleos familiares</h2><p>Adicione convidados, consulte o convite ou encerre o acesso ao painel.</p></div><div className="adminTopActions"><button className="primary" onClick={()=>{setShowAdd(v=>!v);setEditing(null)}}><Plus/> Novo convidado</button><a href="/">Ver convite</a><button onClick={()=>{sessionStorage.removeItem('oliverAdmin');setFamilies([]);setCode('')}}>Sair</button></div></section>
 {editing&&<section className="adminAdd editBox"><div><span className="eyebrow">EDITAR CONVITE</span><h2>Editar núcleo familiar</h2><p>Altere o nome do núcleo, grupo ou integrantes sem modificar o token de acesso.</p></div><div className="adminForm"><label>Nome do núcleo<input value={editing.displayName} onChange={e=>setEditing({...editing,displayName:e.target.value})}/></label><label>Grupo<input value={editing.groupName} onChange={e=>setEditing({...editing,groupName:e.target.value})}/></label><div className="full editGuests"><label>Convidados</label>{editing.guests.map((g,i)=><div className="editGuest" key={g.id||i}><input value={g.name} onChange={e=>setEditing({...editing,guests:editing.guests.map((x,j)=>j===i?{...x,name:e.target.value}:x)})}/><button onClick={()=>setEditing({...editing,guests:editing.guests.filter((_,j)=>j!==i)})}>Remover</button></div>)}<button className="addPerson" onClick={()=>setEditing({...editing,guests:[...editing.guests,{name:''}]})}><Plus/> Adicionar integrante</button></div><div className="full formActions"><button onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" onClick={saveEdit} disabled={saving}>{saving?'Salvando...':'Salvar alterações'}</button></div></div></section>}
 {showAdd&&<section className="adminAdd"><div><span className="eyebrow">NOVO NÚCLEO</span><h2>Adicionar convidados</h2><p>Cadastre a família e os integrantes. Um token de 4 dígitos será criado automaticamente.</p></div><div className="adminForm"><label>Nome do núcleo<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Ex.: Família Silva"/></label><label>Grupo<input value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Ex.: Amigos, Família Gustavo..."/></label><label className="full">Convidados<textarea value={guestText} onChange={e=>setGuestText(e.target.value)} placeholder={'Um nome por linha\nGustavo\nVanessa'}/></label><div className="full formActions"><button onClick={()=>setShowAdd(false)}>Cancelar</button><button className="primary" onClick={addFamily} disabled={saving}>{saving?'Adicionando...':'Adicionar núcleo'}</button></div></div></section>}
 {error&&<div className="error adminError">{error}</div>}
 <section className="confirmationFilter"><div><span className="eyebrow">STATUS DE CONFIRMAÇÃO</span><h2>Consultar convidados e núcleos</h2><p>Selecione um status para verificar quais núcleos e convidados estão em cada situação.</p></div><div className="statusFilters">{[['all','Todos'],['confirmed','Confirmados'],['pending','A confirmar'],['partial','Parcial'],['declined','Recusados']].map(([key,label])=><button key={key} className={statusFilter===key?'active':''} onClick={()=>setStatusFilter(key)}>{label}<b>{statusCounts[key]}</b></button>)}</div></section>
 <div className="adminTools"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar número, núcleo ou convidado"/><span>{shown.length} núcleo{shown.length===1?'':'s'}</span></div>
 <div className="guestList">{shown.map((f,i)=><article className="guestRow" key={f.id}><div className="guestNumber">#{String(f.number||i+1).padStart(2,'0')}</div><div className="guestMain"><div className="guestTitle"><h3>{f.display_name}</h3><span className={'status '+(f.invite_status||'')}>{f.invite_status==='confirmed'?'Confirmado':f.invite_status==='declined'?'Não irá':f.invite_status==='partial'?'Parcial':'Aguardando'}</span></div><div className="guestPeople">{(f.guests||[]).map(g=><span key={g.id} className={'personStatus '+(g.attendance==='yes'?'yes':g.attendance==='no'?'no':'waiting')}>{g.name}<small>{g.attendance==='yes'?'Confirmado':g.attendance==='no'?'Não irá':'A confirmar'}</small></span>)}</div><div className="guestMeta"><span>Token: <b>{f.invite_pin_plain||'— — — —'}</b></span>{f.group_name&&<span>{f.group_name}</span>}<span>Fraldas: <b>{(f.diapers||[]).map(d=>d.diaper_size).join(', ')||'—'}</b></span></div></div><div className="guestActions"><button onClick={()=>beginEdit(f)}><Pencil/> Editar</button><button onClick={()=>resetToken(f)}><RefreshCw/> Resetar token</button><button onClick={()=>copy(f)} disabled={!f.invite_pin_plain}><Copy/> Copiar convite</button><button className="primary" onClick={()=>whatsapp(f)} disabled={!f.invite_pin_plain}><MessageCircle/> WhatsApp</button></div></article>)}</div></div></div>;
}
createRoot(document.getElementById('root')).render(<AdminPanel/>);