import React,{useEffect,useMemo,useRef,useState}from'react';import{createRoot}from'react-dom/client';
import {eventToday, matchesPeriod, deadline, installmentBalance, expenseTotals, planningSnapshot, recordExpensePayment, paymentHistory, reviseExpensePayment, generateInstallments, categoryBudgets, saveExpenseWithActions, paymentForecast, planningCsv, trashPlanningItem, restorePlanningItem, taskDependencies, validateTaskDependencies, duplicatePlanningTask, duplicatePlanningExpense, taskProgress, togglePlanningTask, togglePlanningSubtask, eventSchedule, filterEventSchedule} from './planning-utils.mjs';
import './admin-planning.css';
import {PlanningHistory} from './planning-history.jsx';
import {PlanningDialog as Modal} from './planning-dialog.jsx';
import {usePlanningSync} from './planning-sync.jsx';
import {PlanningTabs,QuoteBoard,QuoteForm,CostPerGuest} from './planning-finance.jsx';
import {contractPlanningQuote} from './planning-utils.mjs';
const KEY='oliverEventPlanningV2',API=(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'')+'/functions/v1/planning-api';
const CATS=['Local','Alimentação','Bebidas','Decoração','Convites','Lembrancinhas','Bolo e doces','Foto/Vídeo','Estrutura','Outros'],PAY=['Pix','Débito','Crédito','Dinheiro','Outros'];
const seed={tasks:[{id:'t1',title:'Fechar quantidade final de convidados',category:'Convites',due:'2026-11-20',status:'todo',priority:'high',responsible:'',notes:'',cost:false},{id:'t2',title:'Definir cardápio e quantidades',category:'Alimentação',due:'2026-11-20',status:'todo',priority:'high',responsible:'',notes:'',cost:true},{id:'t3',title:'Confirmar decoração e montagem',category:'Decoração',due:'2026-11-27',status:'todo',priority:'medium',responsible:'',notes:'',cost:true}],expenses:[]};
const normalize=d=>({history:Array.isArray(d?.history)?d.history:[],quotes:Array.isArray(d?.quotes)?d.quotes:[],guestSettings:d?.guestSettings||{excludeUnder5:true,basis:"confirmed",estimatedGuests:100},trash:Array.isArray(d?.trash)?d.trash:[],budgets:d?.budgets&&typeof d.budgets==='object'&&!Array.isArray(d.budgets)?d.budgets:{},tasks:(d?.tasks||[]).map(t=>({...t,completedAt:t.completedAt||''})),expenses:(d?.expenses||[]).map(e=>({...e,installments:Array.isArray(e.installments)?e.installments.map((p,i)=>({...p,id:p.id||'payment-'+e.id+'-'+i})):(e.planned||e.paid||e.due?[{id:'legacy-'+e.id,label:'Pagamento',amount:Number(e.planned)||0,due:e.due||'',paidAmount:Number(e.paid)||0,paidAt:Number(e.paid)>0?(e.due||''):'',payment:e.payment||'Pix'}]:[])}))});
const readLocal=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return normalize(x&&Array.isArray(x.tasks)&&Array.isArray(x.expenses)?x:seed)}catch{return normalize(seed)}};
const planningApi=async(action,data,expectedRevision)=>{const adminCode=sessionStorage.getItem('oliverAdmin')||'';if(!API||!adminCode)throw new Error('Conecte-se ao painel para usar os documentos.');const form=data instanceof FormData;let body;if(form){data.set('action',action);data.set('adminCode',adminCode);if(expectedRevision!==undefined)data.set('expectedRevision',String(expectedRevision));body=data}else body=JSON.stringify({action,adminCode,expectedRevision,...(['upload','file_url','remove_file'].includes(action)?data:{data})});const r=await fetch(API,{method:'POST',headers:form?undefined:{'Content-Type':'application/json'},body}),j=await r.json();if(!r.ok){const error=new Error(({invalid_file:'Use PDF, JPG, PNG ou WebP de até 5 MB.',target_not_found:'O serviço ou pagamento não está mais disponível.',file_not_found:'Documento não encontrado.',attachment_limit:'Este registro já tem 20 documentos.',unauthorized:'Sua sessão não permite acessar os documentos.',planning_load_failed:'Não foi possível carregar os documentos.',planning_save_failed:'Não foi possível salvar o documento.',upload_failed:'Não foi possível enviar o arquivo.',storage_failed:'Não foi possível acessar o arquivo.',invalid_dependencies:'Confira as dependências: uma ação não pode depender de si mesma ou criar um ciclo.',invalid_quotes:'Confira os fornecedores, valores e datas das cotações.',invalid_guest_settings:'Confira a estimativa e a base do custo por convidado.',conflict:'Outro dispositivo atualizou o planejamento. Resolva as alterações e tente novamente.',upgrade_required:'Atualize esta página para salvar com segurança.'})[j.error]||'Não foi possível concluir. Tente novamente.');error.code=j.error;throw error}return j};
const money=n=>(Number(n)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),id=()=>crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),fmt=d=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'',today=eventToday;
function TaskForm({item,onSave,onDelete,onClose,expenses=[],tasks=[],initialSchedule=false}) {
  const[f,setF]=useState({...{title:'',category:'Outros',due:'',priority:'medium',responsible:'',notes:'',cost:false,eventDate:'2026-12-04',eventTime:'',eventEnd:'',contact:'',place:''},...item,dependsOn:item?.dependsOn||[],subtasks:(item?.subtasks||[]).map(s=>({...s}))}),[scheduled,setScheduled]=useState(initialSchedule||!!item?.eventTime),[error,setError]=useState('');
  const change=(key,value)=>{setF(x=>({...x,[key]:value}));setError('')};
  const setStep=(index,key,value)=>change('subtasks',f.subtasks.map((s,i)=>i===index?{...s,[key]:value}:s));
  return <form onSubmit={e=>{e.preventDefault();if(scheduled&&f.eventEnd&&f.eventEnd<f.eventTime){setError('O horário final deve ser igual ou posterior ao início.');return}if(!f.title.trim())return;const steps=f.subtasks.map(s=>({...s,title:s.title.trim()}));if(steps.some(s=>!s.title)){setError('Preencha a descrição de todas as etapas.');return}try{validateTaskDependencies([...tasks.filter(t=>t.id!==f.id),{...f,id:f.id||'__new_task__',dependsOn:f.dependsOn.filter(Boolean)}])}catch(err){setError(err.message);return}const reopened=f.status==='done'&&(steps.some(s=>!s.done)||taskDependencies(f,tasks).length>0);onSave({...f,title:f.title.trim(),dependsOn:f.dependsOn.filter(Boolean),subtasks:steps,...(!scheduled?{eventDate:'',eventTime:'',eventEnd:'',contact:'',place:''}:{}),...(reopened?{status:'todo',completedAt:''}:{})})}}>
    <h3>{item?.id?'Editar':'Nova'} tarefa</h3><label>Tarefa<input autoFocus required value={f.title} onChange={e=>change('title',e.target.value)}/></label>
    <div className="formGrid"><label>Categoria<select aria-label="Categoria da tarefa" value={f.category} onChange={e=>change('category',e.target.value)}>{CATS.map(x=><option key={x}>{x}</option>)}</select></label><label>Prazo<input type="date" value={f.due} onChange={e=>change('due',e.target.value)}/></label><label>Prioridade<select value={f.priority} onChange={e=>change('priority',e.target.value)}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label><label>Responsável<input value={f.responsible} onChange={e=>change('responsible',e.target.value)}/></label></div>
    <div className="planningDependencyEditor"><b>Depende de outras ações</b><p className="planningFormHint">A conclusão fica bloqueada enquanto houver uma dependência pendente. Remover uma ação mantém o bloqueio até você restaurá-la ou remover o vínculo.</p>{f.dependsOn.map((dependency,index)=><div className="planningDependencyRow" key={index}><select aria-label={`Dependência ${index+1}`} value={dependency} onChange={e=>change('dependsOn',f.dependsOn.map((value,i)=>i===index?e.target.value:value))}><option value="">Escolher ação</option>{dependency&&!tasks.some(t=>t.id===dependency)&&<option value={dependency}>Ação removida</option>}{tasks.filter(t=>t.id!==f.id&&(!f.dependsOn.includes(t.id)||t.id===dependency)).map(t=><option key={t.id} value={t.id}>{t.title}{t.status==='done'?' · Realizada':''}</option>)}</select><button type="button" aria-label={`Remover dependência ${index+1}`} onClick={()=>change('dependsOn',f.dependsOn.filter((_,i)=>i!==index))}>Remover</button></div>)}<button type="button" disabled={f.dependsOn.length>=50||f.dependsOn.includes('')||!tasks.some(t=>t.id!==f.id&&!f.dependsOn.includes(t.id))} onClick={()=>change('dependsOn',[...f.dependsOn,''])}>+ Adicionar dependência</button></div>
    <div className="planningSubtaskEditor"><b>Etapas da ação</b><p className="planningFormHint">Conclua as etapas antes de finalizar a ação.</p>{f.subtasks.map((step,index)=><div className="planningSubtaskEditRow" key={step.id}><input type="checkbox" aria-label={`Etapa ${index+1} concluída`} checked={!!step.done} onChange={e=>setStep(index,'done',e.target.checked)}/><input required aria-label={`Descrição da etapa ${index+1}`} value={step.title} onChange={e=>setStep(index,'title',e.target.value)}/><button type="button" aria-label={`Remover etapa ${index+1}`} onClick={()=>change('subtasks',f.subtasks.filter((_,i)=>i!==index))}>Remover</button></div>)}<button type="button" onClick={()=>change('subtasks',[...f.subtasks,{id:id(),title:'',done:false}])}>+ Adicionar etapa</button></div>
    <label className="checkLine"><input type="checkbox" checked={scheduled} onChange={e=>{setScheduled(e.target.checked);if(e.target.checked&&!f.eventDate)change('eventDate','2026-12-04')}}/> Incluir no cronograma do dia</label>{scheduled&&<div className="planningScheduleEditor"><div className="formGrid"><label>Data do cronograma<input required type="date" value={f.eventDate} onChange={e=>change('eventDate',e.target.value)}/></label><label>Horário de início<input required type="time" value={f.eventTime} onChange={e=>change('eventTime',e.target.value)}/></label><label>Horário final (opcional)<input type="time" value={f.eventEnd} onChange={e=>change('eventEnd',e.target.value)}/></label><label>Contato<input type="tel" value={f.contact} placeholder="Telefone do responsável ou fornecedor" onChange={e=>change('contact',e.target.value)}/></label></div><label>Local / ponto de encontro<input value={f.place} onChange={e=>change('place',e.target.value)}/></label></div>}
    <label>Observação<textarea value={f.notes} onChange={e=>change('notes',e.target.value)}/></label><label className="checkLine"><input type="checkbox" checked={!!f.cost} onChange={e=>setF(x=>({...x,cost:e.target.checked,expenseId:e.target.checked?x.expenseId:''}))}/> Esta tarefa envolve um gasto</label><label>Serviço vinculado<select aria-label="Serviço vinculado" value={f.expenseId||''} onChange={e=>setF(x=>({...x,expenseId:e.target.value,cost:e.target.value?true:x.cost}))}><option value="">Sem vínculo</option>{f.expenseId&&!expenses.some(e=>e.id===f.expenseId)&&<option value={f.expenseId}>Serviço indisponível</option>}{expenses.map(e=><option value={e.id} key={e.id}>{e.description}</option>)}</select></label>{error&&<p className="error" role="alert">{error}</p>}<div className="modalActions">{item?.id&&<button type="button" className="danger" onClick={onDelete}>Excluir</button>}<button type="button" onClick={onClose}>Cancelar</button><button type="submit" className="primary">Salvar</button></div>
  </form>;
}
function TaskDependencies({task,tasks,onEdit}) {
  const pending=taskDependencies(task,tasks);if(!pending.length)return null;
  return <div className="planningDependencyNotice"><b>{task.status==='done'?'Dependência pendente':'Bloqueada por dependência'}</b>{pending.map(t=>t.missing?<span key={t.id}>Ação removida — edite o vínculo ou restaure na lixeira.</span>:<button key={t.id} type="button" aria-label={`Abrir dependência ${t.title}`} onClick={()=>onEdit(t)}>{t.title}</button>)}</div>;
}
function TaskSteps({task,onToggle}) {
  const progress=taskProgress(task);if(!progress.total)return null;
  return <details className="planningTaskSteps"><summary>Etapas · {progress.done}/{progress.total}</summary><progress value={progress.done} max={progress.total} aria-label={`Progresso de ${task.title}`}/>{task.subtasks.map(step=><label key={step.id}><input type="checkbox" checked={!!step.done} onChange={()=>onToggle(task.id,step.id)}/><span>{step.title}</span></label>)}</details>;
}
function EventSchedule({tasks,onAdd,onEdit,onToggle}) {
  const[date,setDate]=useState('2026-12-04'),[search,setSearch]=useState(''),[owner,setOwner]=useState('all'),[status,setStatus]=useState('all'),[from,setFrom]=useState(''),[until,setUntil]=useState(''),[filtersOpen,setFiltersOpen]=useState(false);
  const all=eventSchedule(tasks,date),rows=filterEventSchedule(tasks,date,{search,owner,status,from,until});
  const owners=[...new Set(all.map(t=>t.responsible?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
  const filterCount=[owner!=='all',status!=='all',!!from,!!until].filter(Boolean).length,filtered=!!search.trim()||filterCount>0;
  const invalidRange=from&&until&&from>until;
  const clear=()=>{setSearch('');setOwner('all');setStatus('all');setFrom('');setUntil('')};
  return <section className="planningEventSchedule" aria-label="Cronograma do dia"><div className="planningSubviewHeading"><h4>Cronograma do dia</h4><span role="status">{rows.length} de {all.length} ação(ões) · {fmt(date)}</span></div><div className="planningScheduleHead"><label>Data do cronograma<input aria-label="Data do cronograma" type="date" value={date} onChange={e=>{setDate(e.target.value);setOwner('all')}}/></label><button type="button" onClick={()=>onAdd(date)}>+ Adicionar horário</button></div>
    <div className="planningScheduleToolbar"><label>Buscar no cronograma<input aria-label="Buscar no cronograma" type="search" placeholder="Ação, responsável, local ou contato" value={search} onChange={e=>setSearch(e.target.value)}/></label><button type="button" className="planningFilterToggle" aria-expanded={filtersOpen} aria-controls="planning-schedule-filters" onClick={()=>setFiltersOpen(value=>!value)}>Filtros{filterCount?' · '+filterCount:''}</button></div>
    {filtersOpen&&<div id="planning-schedule-filters" className="planningScheduleFilters"><label>Responsável<select aria-label="Responsável do cronograma" value={owner} onChange={e=>setOwner(e.target.value)}><option value="all">Todos</option><option value="unassigned">Sem responsável</option>{owner!=='all'&&owner!=='unassigned'&&!owners.includes(owner)&&<option value={owner}>{owner} · Não disponível nesta data</option>}{owners.map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Situação<select aria-label="Situação do cronograma" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todas</option><option value="open">A realizar</option><option value="done">Realizadas</option><option value="blocked">Bloqueadas por dependência</option></select></label><label>A partir de<input aria-label="Horário inicial do cronograma" type="time" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input aria-label="Horário final do cronograma" type="time" value={until} onChange={e=>setUntil(e.target.value)}/></label><small>A faixa considera o horário de início de cada ação.</small></div>}
    {invalidRange&&<p className="error" role="alert">O horário final deve ser igual ou posterior ao inicial.</p>}
    {filtered&&<button type="button" className="planningScheduleClear" onClick={clear}>Limpar filtros do cronograma</button>}
    {rows.length?<ol className="planningScheduleList">{rows.map(t=><li key={t.id} className={t.status==='done'?'done':''}><time>{t.eventTime}{t.eventEnd?' – '+t.eventEnd:''}</time><div><b>{t.title}</b><span>{t.responsible||'Sem responsável'}{t.place?' · '+t.place:''}</span><TaskDependencies task={t} tasks={tasks} onEdit={onEdit}/>{t.contact&&<span>Contato: {t.contact}</span>}{t.subtasks?.length>0&&<span>Etapas: {taskProgress(t).done}/{taskProgress(t).total}</span>}</div><button type="button" aria-label={`Editar horário de ${t.title}`} onClick={()=>onEdit(t)}>Editar</button><button type="button" aria-label={`${t.status==='done'?'Reabrir':'Concluir'} horário de ${t.title}`} disabled={t.status!=='done'&&(taskProgress(t).pending||taskDependencies(t,tasks).length>0)} onClick={()=>onToggle(t)}>{t.status==='done'?'Reabrir':'Concluir'}</button></li>)}</ol>:<p className="planningFormHint">{all.length?'Nenhuma ação corresponde aos filtros selecionados.':'Nenhum horário cadastrado para este dia.'}</p>}</section>;
}
function ExpenseForm({item,onSave,onDelete,onClose,linkedTasks=[],tasks=[]}) {
  const base=item||{description:'',category:'Outros',supplier:'',notes:'',installments:[]};
  const[f,setF]=useState({...base,contracted:expenseTotals(base).planned,installments:(base.installments||[]).map(p=>({...p}))}),[error,setError]=useState(''),[generator,setGenerator]=useState(false),[count,setCount]=useState(3),[firstDue,setFirstDue]=useState(today),[preview,setPreview]=useState([]);
  const[actionIds,setActionIds]=useState(linkedTasks.length?linkedTasks.map(t=>t.id):['']);
  const change=(k,v)=>{setF(x=>({...x,[k]:v}));setError('');setPreview([])};
  const add=()=>change('installments',[...f.installments,{id:id(),label:`Parcela ${f.installments.length+1}`,amount:'',due:'',paidAmount:0,paidAt:'',payment:'Pix'}]);
  const setInst=(i,k,v)=>change('installments',f.installments.map((p,j)=>j===i?{...p,[k]:v,...(['paidAmount','paidAt','payment'].includes(k)?{payments:undefined}:{})}:p));
  const totals=expenseTotals(f);
  const submit=e=>{
    e.preventDefault();
    if(!f.description.trim())return;
    if(Math.round(totals.scheduled*100)>Math.round(totals.planned*100)){setError('A soma das parcelas não pode superar o valor contratado. Ajuste o contrato ou os pagamentos.');return}
    onSave({...f,linkedActionIds:actionIds.filter(Boolean),description:f.description.trim(),contracted:totals.planned,planned:totals.planned,paid:totals.paid,installments:f.installments.map(p=>({...p,amount:Number(p.amount)||0,paidAmount:Number(p.paidAmount)||0}))});
  };
  return <form onSubmit={submit}><h3>{item?.id?'Editar':'Novo'} gasto</h3><div className="planningActionLinks">{actionIds.map((selected,index)=><div className="planningActionLinkRow" key={index}><label>{index===0?'Ação vinculada':'Outra ação vinculada'}<select aria-label={`Ação vinculada ${index+1}`} value={selected} onChange={e=>setActionIds(ids=>ids.map((v,i)=>i===index?e.target.value:v))}><option value="">Não vincular ação</option>{[...tasks].sort((a,b)=>a.title.localeCompare(b.title,'pt-BR')).map(t=><option key={t.id} value={t.id} disabled={actionIds.includes(t.id)&&selected!==t.id}>{t.title} · {t.status==='done'?'Realizada':'A realizar'}{t.expenseId&&t.expenseId!==item?.id?' · Outro serviço':''}</option>)}</select>{selected&&tasks.find(t=>t.id===selected)?.expenseId&&tasks.find(t=>t.id===selected)?.expenseId!==item?.id&&<small className="planningFormHint">Ao salvar, esta ação passará a se vincular a este serviço.</small>}</label>{(selected||actionIds.length>1)&&<button type="button" className="planningRemoveLink" aria-label={`Remover vínculo ${index+1}`} onClick={()=>setActionIds(ids=>{const remaining=ids.filter((_,i)=>i!==index);return remaining.length?remaining:['']})}>Remover</button>}</div>)}{tasks.length>actionIds.filter(Boolean).length&&<button type="button" disabled={actionIds.includes('')} onClick={()=>setActionIds(ids=>[...ids,''])}>+ Vincular outra ação</button>}<small className="planningFormHint">O vínculo será aplicado ao salvar. Concluir uma ação não altera os pagamentos.</small></div>
    <label>Descrição<input autoFocus required value={f.description} onChange={e=>change('description',e.target.value)}/></label>
    <div className="formGrid"><label>Categoria<select value={f.category} onChange={e=>change('category',e.target.value)}>{CATS.map(x=><option key={x}>{x}</option>)}</select></label><label>Fornecedor<input value={f.supplier||''} onChange={e=>change('supplier',e.target.value)}/></label></div>
    <label>Valor total contratado<input type="number" min="0" step="0.01" required value={f.contracted} onChange={e=>change('contracted',e.target.value)}/><small className="planningFormHint">Informe o valor completo do serviço. As parcelas podem ser programadas aos poucos.</small></label>
    <div className="installmentHead"><div><b>Pagamentos / parcelas</b><small>Programado: {money(totals.scheduled)} · Sem programação: {money(totals.unallocated)}</small></div><button type="button" onClick={add}>+ Adicionar pagamento</button></div>
    <div className="planningGenerator"><button type="button" aria-expanded={generator} onClick={()=>setGenerator(x=>!x)}>Parcelar automaticamente</button>{generator&&<div>
      <p className="planningFormHint">Divida os {money(totals.unallocated)} sem programação em parcelas mensais. Os pagamentos existentes serão mantidos.</p>
      <div className="formGrid"><label>Quantidade de parcelas<input type="number" min="1" max="60" step="1" value={count} onChange={e=>{setCount(e.target.value);setPreview([])}}/></label><label>Primeiro vencimento<input type="date" value={firstDue} onChange={e=>{setFirstDue(e.target.value);setPreview([])}}/></label></div>
      <button type="button" disabled={totals.unallocated<=0} onClick={()=>{try{setPreview(generateInstallments({amount:totals.unallocated,count,firstDue,startIndex:f.installments.length+1},id));setError('')}catch(err){setPreview([]);setError(err.message)}}}>Prévia das parcelas</button>
      {preview.length>0&&<><ul className="planningInstallmentPreview" aria-label="Prévia das parcelas">{preview.map(p=><li key={p.id}><span>{p.label} · {fmt(p.due)}</span><b>{money(p.amount)}</b></li>)}</ul><button type="button" className="primary" onClick={()=>change('installments',[...f.installments,...preview])}>Adicionar {preview.length} parcelas</button></>}
      <small className="planningFormHint">Quando o mês não tiver o dia escolhido, o vencimento será no último dia do mês.</small>
    </div>}</div>
    {f.installments.some(p=>p.payments?.length>0)&&<p className="planningFormHint">Para corrigir pagamentos já registrados, use Editar ou Estornar no histórico do serviço.</p>}<div className="installmentEditor">{f.installments.map((p,i)=><div className="installmentRow" key={p.id||i}>
      <input aria-label={`Nome da parcela ${i+1}`} placeholder="Ex.: Sinal" value={p.label||''} onChange={e=>setInst(i,'label',e.target.value)}/>
      <input aria-label={`Valor da parcela ${i+1}`} type="number" min="0" step="0.01" placeholder="Valor" value={p.amount} onChange={e=>setInst(i,'amount',e.target.value)}/>
      <input aria-label={`Vencimento da parcela ${i+1}`} type="date" value={p.due||''} onChange={e=>setInst(i,'due',e.target.value)}/>
      <input disabled={!!p.payments?.length} aria-label={`Valor pago da parcela ${i+1}`} type="number" min="0" step="0.01" placeholder="Pago" value={p.paidAmount||''} onChange={e=>setInst(i,'paidAmount',e.target.value)}/>
      <input disabled={!!p.payments?.length} aria-label={`Data de pagamento da parcela ${i+1}`} type="date" value={p.paidAt||''} onChange={e=>setInst(i,'paidAt',e.target.value)}/>
      <select disabled={!!p.payments?.length} aria-label={`Meio de pagamento da parcela ${i+1}`} value={p.payment||'Pix'} onChange={e=>setInst(i,'payment',e.target.value)}>{PAY.map(x=><option key={x}>{x}</option>)}</select>
      <button type="button" className="removeInstallment" aria-label={`Remover parcela ${i+1}`} onClick={()=>change('installments',f.installments.filter((_,j)=>j!==i))}>×</button>
    </div>)}</div>
    {!f.installments.length&&<div className="planningEmpty">O valor contratado ficará como saldo sem programação até você cadastrar parcelas ou registrar um pagamento.</div>}
    <label>Observação<textarea value={f.notes||''} onChange={e=>change('notes',e.target.value)}/></label>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="modalActions">{item?.id&&<button type="button" className="danger" onClick={onDelete}>Excluir</button>}<button type="button" onClick={onClose}>Cancelar</button><button type="submit" className="primary">Salvar</button></div>
  </form>;
}
function PaymentForm({item,onSave,onClose,initialInstallmentId}) {
  const totals=expenseTotals(item),options=(item.installments||[]).filter(p=>installmentBalance(p)>0).map(p=>({id:p.id,label:p.label||'Pagamento',balance:installmentBalance(p)}));
  if(totals.unallocated>0)options.push({id:'__unallocated__',label:'Saldo sem programação',balance:totals.unallocated});
  const initial=options.find(p=>p.id===initialInstallmentId)||options[0];
  const[selection,setSelection]=useState(initial?.id||''),[amount,setAmount]=useState(initial?.balance||''),[paidAt,setPaidAt]=useState(today),[payment,setPayment]=useState('Pix'),[error,setError]=useState('');
  const selected=options.find(p=>p.id===selection);
  return <form onSubmit={e=>{e.preventDefault();try{onSave(recordExpensePayment(item,{installmentId:selection,amount,paidAt,payment},id))}catch(err){setError(err.message)}}}>
    <h3>Registrar pagamento</h3><p className="planningPaymentIntro">{item.description} · Saldo total {money(totals.balance)}</p>
    <label>Parcela<select aria-label="Parcela" value={selection} onChange={e=>{setSelection(e.target.value);setAmount(options.find(p=>p.id===e.target.value)?.balance||'');setError('')}}>{options.map(p=><option key={p.id} value={p.id}>{p.label} · {money(p.balance)}</option>)}</select></label>
    <div className="formGrid"><label>Valor do pagamento<input autoFocus required type="number" min="0.01" max={selected?.balance||0} step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setError('')}}/></label><label>Data do pagamento<input required type="date" max={today()} value={paidAt} onChange={e=>setPaidAt(e.target.value)}/></label></div>
    <label>Meio de pagamento<select aria-label="Meio de pagamento" value={payment} onChange={e=>setPayment(e.target.value)}>{PAY.map(x=><option key={x}>{x}</option>)}</select></label>
    <p className="planningFormHint">O valor será somado aos pagamentos já registrados. O serviço será quitado quando não houver saldo.</p>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="modalActions"><button type="button" onClick={onClose}>Cancelar</button><button type="submit" className="primary" disabled={!selected}>Registrar pagamento</button></div>
  </form>;
}
function PaymentRevisionForm({item,installmentId,paymentId,action,onSave,onClose}) {
  const installment=(item.installments||[]).find(p=>p.id===installmentId),entry=paymentHistory(installment||{}).find(h=>h.id===paymentId);
  const[f,setF]=useState({amount:entry?.amount||'',paidAt:entry?.paidAt||today(),payment:entry?.payment||'Pix',reason:''}),[error,setError]=useState('');
  const change=(key,value)=>{setF(x=>({...x,[key]:value}));setError('')};
  const reversing=action==='reverse',other=paymentHistory(installment||{}).filter(h=>h.id!==paymentId&&!h.reversedAt).reduce((sum,h)=>sum+(Number(h.amount)||0),0);
  return <form onSubmit={e=>{e.preventDefault();try{onSave(reviseExpensePayment(item,{installmentId,paymentId,action,...f}))}catch(err){setError(err.message)}}}>
    <h3>{reversing?'Estornar':'Editar'} pagamento</h3><p className="planningPaymentIntro">{item.description} · {installment?.label||'Pagamento'} · {money(entry?.amount)}</p>
    {reversing?<p className="planningFormHint">O lançamento continuará no histórico como estornado. Seu valor deixará de contar como pago e voltará ao saldo a quitar.</p>:<><div className="formGrid"><label>Valor do pagamento<input autoFocus required type="number" min="0.01" step="0.01" max={Math.max(0,(Number(installment?.amount)||0)-other).toFixed(2)} value={f.amount} onChange={e=>change('amount',e.target.value)}/></label><label>Data do pagamento<input required type="date" max={today()} value={f.paidAt} onChange={e=>change('paidAt',e.target.value)}/></label></div><label>Meio de pagamento<select aria-label="Meio de pagamento" value={f.payment} onChange={e=>change('payment',e.target.value)}>{PAY.map(x=><option key={x}>{x}</option>)}</select></label></>}
    <label>{reversing?'Motivo do estorno':'Motivo da correção (opcional)'}<textarea autoFocus={reversing} required={reversing} value={f.reason} onChange={e=>change('reason',e.target.value)}/></label>
    {error&&<p className="error" role="alert">{error}</p>}
    <div className="modalActions"><button type="button" onClick={onClose}>Cancelar</button><button type="submit" className={reversing?'danger':'primary'} disabled={!entry||!!entry.reversedAt}>{reversing?'Confirmar estorno':'Salvar correção'}</button></div>
  </form>;
}
const PERIODS=[['all','Todos os períodos'],['today','Hoje'],['next7','Próximos 7 dias'],['next30','Próximos 30 dias'],['overdue','Vencidos'],['undated','Sem data']];
const searchText=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function PeriodFilter({value,onChange,label='Período',paid=false}) {
  const options=paid?[['all','Todos os períodos'],['today','Hoje'],['last7','Últimos 7 dias'],['last30','Últimos 30 dias'],['undated','Sem data']]:PERIODS;
  return <label>{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>;
}
function DueBadge({date,currentDay}) {
  const info=deadline(date,currentDay);
  return <span className={'planningDeadline '+info.tone}>{info.label}</span>;
}
function FilterToolbar({search,onSearch,placeholder,open,onToggle,count,sort,onSort,sortLabel,options,filterId}) {
  return <div className="planningFilterToolbar"><label className="planningSearch">Buscar<input aria-label="Buscar" placeholder={placeholder} value={search} onChange={e=>onSearch(e.target.value)}/></label><button type="button" className={'planningFilterToggle '+(count?'hasFilters':'')} aria-expanded={open} aria-controls={filterId} onClick={onToggle}>Filtrar{count>0?' · '+count:''} <span aria-hidden="true">{open?'▴':'▾'}</span></button><label className="planningSort">Ordenar<select aria-label={sortLabel} value={sort} onChange={e=>onSort(e.target.value)}>{options.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>;
}
function BudgetForm({budgets,onSave,onClose}) {
  const [values,setValues]=useState({...budgets});
  return <form onSubmit={e=>{e.preventDefault();const next={...budgets};CATS.forEach(c=>{if(values[c]==null||values[c]==='')delete next[c];else next[c]=Math.round(Number(values[c])*100)/100});onSave(next)}}>
    <h3>Orçamento por categoria</h3><p className="planningFormHint">Defina quanto pretende gastar. Deixe em branco as categorias sem limite; zero significa não reservar verba.</p>
    <div className="formGrid">{CATS.map(c=><label key={c}>{c}<input aria-label={`Orçamento de ${c}`} type="number" min="0" step="0.01" placeholder="Sem limite" value={values[c]??''} onChange={e=>setValues(v=>({...v,[c]:e.target.value}))}/></label>)}</div>
    <div className="modalActions"><button type="button" onClick={onClose}>Cancelar</button><button type="submit" className="primary">Salvar orçamento</button></div>
  </form>;
}
function BudgetOverview({expenses,budgets,onEdit}) {
  const rows=categoryBudgets(expenses,budgets,CATS),visible=rows.filter(r=>r.budget!==null||r.contracted>0);
  const planned=rows.reduce((s,r)=>s+Math.round((r.budget||0)*100),0)/100,exceeded=rows.filter(r=>r.remaining!==null&&r.remaining<0).length;
  return <section className="planningBudget" aria-label="Orçamento por categoria"><div className="planningSubviewHeading"><h4>Orçamento por categoria</h4><span>{visible.length?money(planned)+' definido':'Definir limites'}{exceeded>0?` · ${exceeded} acima do limite`:''}</span></div>
    <p className="planningFormHint">Compare o limite com todos os serviços contratados, incluindo os quitados. Os totais não dependem dos filtros abaixo.</p><button type="button" onClick={onEdit}>Editar orçamento</button>
    {visible.length?<div className="planningBudgetRows">{visible.map(r=><div key={r.category} className={'planningBudgetRow '+(r.remaining!==null&&r.remaining<0?'overBudget':'')}><b>{r.category}</b><span>Contratado: {money(r.contracted)}</span><span>{r.budget===null?'Sem limite definido':'Limite: '+money(r.budget)}</span>{r.budget!==null&&<><progress aria-label={`Uso do orçamento de ${r.category}`} max={Math.max(r.budget,r.contracted,1)} value={r.contracted}/><strong>{r.remaining<0?money(-r.remaining)+' acima do limite':money(r.remaining)+' disponível'}</strong></>}</div>)}</div>:<p className="planningFormHint">Defina os limites para acompanhar o orçamento do chá.</p>}
  </section>;
}
function UpcomingPayments({expenses,currentDay,onPay,onEdit}) {
  const [period,setPeriod]=useState('next7'),forecast=paymentForecast(expenses,currentDay);
  const pending=expenses.flatMap(expense=>[
    ...(expense.installments||[]).map(p=>({...p,expense,balance:installmentBalance(p)})).filter(p=>p.balance>0),
    ...(expenseTotals(expense).unallocated>0?[{id:'__unallocated__',label:'Saldo sem programação',due:'',expense,balance:expenseTotals(expense).unallocated}]:[])
  ]).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999')||a.expense.description.localeCompare(b.expense.description,'pt-BR'));
  const rows=pending.filter(p=>matchesPeriod(p.due,period,currentDay)),total=rows.reduce((sum,p)=>sum+Math.round(p.balance*100),0)/100;
  return <section className="planningUpcoming" aria-label="Próximos pagamentos"><div className="planningSubviewHeading"><h4>Agenda de pagamentos</h4><span>7 dias: {money(forecast.total7)} · 30 dias: {money(forecast.total30)}</span></div>
    <p className="planningFormHint">Consulte o saldo restante de cada parcela. Pagamentos parciais continuam aqui até a quitação.</p>
    <PeriodFilter label="Período dos pagamentos" value={period} onChange={setPeriod}/>
    <p className="planningPaymentSummary" role="status">{rows.length} pendência(s) · <b>{money(total)}</b> no período selecionado</p>
    {rows.length?<ul className="planningUpcomingList">{rows.map(p=><li key={p.expense.id+'-'+p.id}><div><button type="button" className="planningAgendaService" aria-label={`Abrir serviço ${p.expense.description}`} onClick={()=>onEdit(p.expense)}>{p.expense.description}</button><span>{p.label||'Parcela'} · {p.due?fmt(p.due):'Sem vencimento'}</span>{p.due&&<DueBadge date={p.due} currentDay={currentDay}/>}</div><strong>{money(p.balance)}</strong><div className="planningAgendaActions"><button type="button" aria-label={`Pagar ${p.label||'parcela'} de ${p.expense.description}`} onClick={()=>onPay(p.expense,p.id)}>Pagar</button>{!p.due&&<button type="button" aria-label={`Programar ${p.label||'parcela'} de ${p.expense.description}`} onClick={()=>onEdit(p.expense)}>Programar</button>}</div></li>)}</ul>:<p className="planningFormHint">Nenhum pagamento pendente neste período.</p>}
  </section>;
}

function ExportPlanningForm({data,currentDay,onClose}) {
  const[section,setSection]=useState('expenses'),[downloaded,setDownloaded]=useState(false);
  const download=()=>{const url=URL.createObjectURL(new Blob([planningCsv(data,section,currentDay)],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`planejamento-${section}-${currentDay}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloaded(true)};
  return <form onSubmit={e=>{e.preventDefault();download()}}><h3>Exportar planejamento</h3><p className="planningFormHint">Baixe os dados em CSV para abrir no Excel. A exportação inclui todos os registros da seção, independentemente dos filtros.</p><label>Conteúdo da exportação<select aria-label="Conteúdo da exportação" value={section} onChange={e=>{setSection(e.target.value);setDownloaded(false)}}><option value="expenses">Serviços e saldos</option><option value="tasks">Ações</option><option value="schedule">Cronograma do dia</option><option value="payments">Parcelas e histórico de pagamentos</option><option value="budgets">Orçamento por categoria</option><option value="quotes">Cotações de fornecedores</option></select></label>{section==='payments'&&<p className="planningFormHint">Cada registro do histórico ocupa uma linha. Valores da parcela se repetem nessas linhas; estornos estão identificados e não contam no valor pago ativo.</p>}{downloaded&&<p role="status" className="planningFormHint">Arquivo gerado.</p>}<div className="modalActions"><button type="button" onClick={onClose}>Fechar</button><button type="submit" className="primary">Baixar CSV</button></div></form>;
}
function TrashForm({entries,onRestore,onClose}) {
  const[error,setError]=useState('');
  return <div><h3>Lixeira do planejamento</h3><p className="planningFormHint">Os registros excluídos deixam de contar nos totais. Restaurar recupera os dados, pagamentos e documentos. Vínculos já usados por outro serviço serão mantidos.</p>{error&&<p className="error" role="alert">{error}</p>}{entries.length?<ul className="planningTrashList">{entries.map(entry=><li key={entry.id}><div><b>{entry.item.title||entry.item.description}</b><span>{entry.type==='task'?'Ação':entry.type==='quote'?'Cotação':'Serviço'} · Excluído em {fmt(eventToday(new Date(entry.deletedAt)))}</span>{entry.type==='expense'&&<small>Contratado: {money(expenseTotals(entry.item).planned)} · Pago: {money(expenseTotals(entry.item).paid)}</small>}</div><button type="button" aria-label={`Restaurar ${entry.item.title||entry.item.description}`} onClick={()=>{try{onRestore(entry.id);setError('')}catch(err){setError(err.message)}}}>Restaurar</button></li>)}</ul>:<p className="planningEmpty">A lixeira está vazia.</p>}<div className="modalActions"><button type="button" onClick={onClose}>Fechar</button></div></div>;
}
function AttachmentManager({item,installmentId,paymentId,onChange,onClose,sync,onBusy,documentApi}) {
  const[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const changeBusy=value=>{setBusy(value);onBusy(value)};
  const entry=paymentId?paymentHistory((item.installments||[]).find(p=>p.id===installmentId)||{}).find(h=>h.id===paymentId):null;
  const attachments=paymentId?entry?.attachments||[]:item.attachments||[];
  const target={expenseId:item.id,installmentId:installmentId||'',paymentId:paymentId||''};
  const upload=async file=>{if(!file)return;if(file.size>5*1024*1024||!['application/pdf','image/jpeg','image/png','image/webp'].includes(file.type)){setError('Use PDF, JPG, PNG ou WebP de até 5 MB.');return}changeBusy(true);setError('');setMessage('');try{const form=new FormData();Object.entries(target).forEach(([k,v])=>form.set(k,v));form.set('file',file);const result=await documentApi('upload',form);onChange(result.expense,result.revision);setMessage('Documento anexado.')}catch(err){setError(err.message)}finally{changeBusy(false)}};
  const open=async document=>{changeBusy(true);setError('');const win=window.open('about:blank','_blank');if(win)win.opener=null;try{const result=await planningApi('file_url',{path:document.path});if(win)win.location.replace(result.url);else setError('Permita abrir uma nova aba para visualizar o documento.')}catch(err){win?.close();setError(err.message)}finally{changeBusy(false)}};
  const remove=async document=>{if(!confirm('Remover este documento? O arquivo será excluído permanentemente.'))return;changeBusy(true);setError('');setMessage('');try{const result=await documentApi('remove_file',{...target,path:document.path});onChange(result.expense,result.revision);setMessage('Documento removido.')}catch(err){setError(err.message)}finally{changeBusy(false)}};
  return <div><h3>{paymentId?'Comprovantes do pagamento':'Documentos do serviço'}</h3><p className="planningPaymentIntro">{item.description}{entry?' · '+money(entry.amount)+(entry.reversedAt?' · Estornado':''):''}</p><p className="planningFormHint">PDF, JPG, PNG ou WebP de até 5 MB. Os documentos têm acesso privado.</p>{sync!=='synced'&&<p className="planningFormHint">Aguarde a sincronização para anexar documentos.</p>}
    <label className="planningFileInput">{busy?'Processando…':'Anexar documento'}<input aria-label="Anexar documento" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={busy||sync!=='synced'||attachments.length>=20} onChange={e=>{upload(e.target.files?.[0]);e.target.value=''}}/></label>
    {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="planningFormHint" role="status">{message}</p>}
    {attachments.length?<ul className="planningDocumentList">{attachments.map(document=><li key={document.path}><div><b>{document.name}</b><span>{(document.size/1024).toFixed(0)} KB · {fmt(eventToday(new Date(document.uploadedAt)))}</span></div><button type="button" disabled={busy} aria-label={`Abrir ${document.name}`} onClick={()=>open(document)}>Abrir</button><button type="button" disabled={busy||sync!=='synced'} className="danger" aria-label={`Remover documento ${document.name}`} onClick={()=>remove(document)}>Remover</button></li>)}</ul>:<p className="planningEmpty">Nenhum documento anexado.</p>}<div className="modalActions"><button type="button" disabled={busy} onClick={onClose}>Fechar</button></div>
  </div>;
}
function ConflictDetails({value,field}) {
  if(value===undefined)return <p>Registro removido</p>;
  if(typeof value==='number')return <p>{field.startsWith('budgets:')?money(value):value}</p>;if(typeof value==='boolean'||typeof value==='string')return <p>{typeof value==='boolean'?(value?'Sim':'Não'):value}</p>;
  const item=value.item||value;
  const fields=[['Categoria',item.category],['Responsável',item.responsible],['Fornecedor',item.supplier],['Situação',item.status==='done'?'Realizada':item.status?'A realizar':''],['Prioridade',({high:'Alta',medium:'Média',low:'Baixa'})[item.priority]],['Prazo',fmt(item.due)],['Cronograma',[fmt(item.eventDate),item.eventTime,item.eventEnd].filter(Boolean).join(' · ')],['Contato',item.contact],['Local',item.place],['Serviço vinculado',item.expenseId?'Sim':'Não'],['Observação',item.notes]];
  return <div className="planningConflictDetails">{fields.filter(([,v])=>v).map(([label,v])=><p key={label}><b>{label}:</b> {v}</p>)}{item.subtasks?.map(step=><p key={step.id}>{step.done?'Concluída':'Pendente'}: {step.title}</p>)}{item.installments?.map(p=><div key={p.id}><p><b>{p.label||'Parcela'}:</b> {money(p.amount)} · Pago: {money(p.paidAmount)} · Vencimento: {fmt(p.due)||'Sem data'}</p>{paymentHistory(p).map(h=><p key={h.id}>{h.reversedAt?'Estornado':'Pagamento'}: {money(h.amount)} · {fmt(h.paidAt)} · {h.payment}{h.reversalReason?' · '+h.reversalReason:''}</p>)}</div>)}{[...(item.attachments||[]),...(item.installments||[]).flatMap(p=>(p.payments||[]).flatMap(h=>h.attachments||[]))].map(d=><p key={d.id}>Documento: {d.name}</p>)}{item.proposals?.map(p=><p key={p.id}>{p.supplier} · {money(p.amount)} · {p.terms}{p.validUntil?' · Validade: '+fmt(p.validUntil):''}</p>)}{value.deletedAt&&<p>Enviado à lixeira em {new Date(value.deletedAt).toLocaleString('pt-BR')}</p>}</div>;
}
function ConflictReview({conflict,onResolve}) {
  const[choices,setChoices]=useState({});
  const describe=value=>value===undefined?'Registro removido':typeof value==='number'?money(value):typeof value==='boolean'?(value?'Sim':'Não'):typeof value==='string'?({confirmed:'Convidados confirmados',estimate:'Estimativa de público'}[value]||value):[value.title||value.description||value.item?.title||value.item?.description,value.responsible,value.due?`Prazo: ${fmt(value.due)}`:'',value.eventTime?`Horário: ${value.eventTime}`:'',value.status==='done'?'Realizada':'',value.subtasks?.length?`Etapas: ${taskProgress(value).done}/${taskProgress(value).total}`:'',value.installments?`Contratado: ${money(expenseTotals(value).planned)} · Pago: ${money(expenseTotals(value).paid)}`:'',value.notes].filter(Boolean).join(' · ');
  return <section className="planningConflict" role="alert"><h3>Este planejamento foi alterado em outro dispositivo</h3><p>As alterações em registros diferentes serão combinadas. Para os registros abaixo, escolha a versão que deseja manter antes de continuar.</p>{conflict.conflicts.map(c=><fieldset key={c.key}><legend>{c.label}</legend>{[['local','Minha edição',c.local],['remote','Outro dispositivo',c.remote]].map(([value,label,item])=><label key={value}><input type="radio" name={c.key} checked={choices[c.key]===value} onChange={()=>setChoices(x=>({...x,[c.key]:value}))}/><span><b>{label}</b><small>{c.key==='guestSettings:estimatedGuests'&&typeof item==='number'?item+' pessoas':describe(item)}</small><details><summary>Ver dados completos</summary><ConflictDetails value={item} field={c.key}/></details></span></label>)}</fieldset>)}<button type="button" className="primary" disabled={conflict.conflicts.some(c=>!choices[c.key])} onClick={()=>onResolve(choices)}>Aplicar escolhas e sincronizar</button></section>;
}
function Planning(){
  const[data,setData]=useState(readLocal),[modal,setModal]=useState(null);
  const {sync,conflict,resolve,retry,documentApi,acceptExpense}=usePlanningSync({data,setData,api:planningApi,normalize,storageKey:KEY});
  const[taskSearch,setTaskSearch]=useState(''),[taskCat,setTaskCat]=useState('all'),[taskView,setTaskView]=useState('open'),[taskOwner,setTaskOwner]=useState('all'),[taskPeriod,setTaskPeriod]=useState('all'),[taskStatus,setTaskStatus]=useState('all');
  const[expenseSearch,setExpenseSearch]=useState(''),[expenseCat,setExpenseCat]=useState('all'),[expenseView,setExpenseView]=useState('open'),[expensePeriod,setExpensePeriod]=useState('all'),[expenseStatus,setExpenseStatus]=useState('all');
  const[currentDay,setCurrentDay]=useState(today);
  const[taskSection,setTaskSection]=useState('checklist'),[financeSection,setFinanceSection]=useState('services');
  const[taskFiltersOpen,setTaskFiltersOpen]=useState(false),[expenseFiltersOpen,setExpenseFiltersOpen]=useState(false),[taskSort,setTaskSort]=useState('due'),[expenseSort,setExpenseSort]=useState('due');
  const taskPanel=useRef(null),expensePanel=useRef(null);
  useEffect(()=>{const refresh=()=>setCurrentDay(today()),clock=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{clearInterval(clock);window.removeEventListener('focus',refresh)}},[]);
  useEffect(()=>{if(conflict)setModal(null)},[conflict]);
  const summary=useMemo(()=>planningSnapshot(data,currentDay),[data,currentDay]);
  const owners=[...new Set(data.tasks.map(t=>t.responsible?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
  const taskCounts={open:data.tasks.filter(t=>t.status!=='done').length,done:data.tasks.filter(t=>t.status==='done').length};
  const tasks=data.tasks.filter(t=>
    (taskView==='done'?t.status==='done':t.status!=='done')&&
    (taskCat==='all'||t.category===taskCat)&&
    (taskOwner==='all'||(taskOwner==='unassigned'?!t.responsible?.trim():t.responsible?.trim()===taskOwner))&&
    searchText(`${t.title} ${t.responsible||''} ${t.notes||''}`).includes(searchText(taskSearch))&&
    matchesPeriod(t.due,taskPeriod,currentDay)&&
    (taskStatus==='all'||(taskStatus==='overdue'&&matchesPeriod(t.due,'overdue',currentDay))||(taskStatus==='undated'&&!t.due)||(taskStatus==='blocked'&&taskDependencies(t,data.tasks).length>0))
  ).sort((a,b)=>taskSort==='completed'?(b.completedAt||'').localeCompare(a.completedAt||''):(taskSort==='title'?a.title.localeCompare(b.title,'pt-BR'):taskSort==='priority'?({high:0,medium:1,low:2}[a.priority]??3)-({high:0,medium:1,low:2}[b.priority]??3)||(a.due||'9999').localeCompare(b.due||'9999'):(a.due||'9999').localeCompare(b.due||'9999')));
  // A service is settled only when every installment has no remaining balance.
  const allExpenses=data.expenses.map(e=>({...e,totals:expenseTotals(e,currentDay)}));
  const expenseCounts={open:allExpenses.filter(e=>e.totals.state!=='paid').length,paid:allExpenses.filter(e=>e.totals.state==='paid').length};
  const settledValue=allExpenses.filter(e=>e.totals.state==='paid').reduce((sum,e)=>sum+e.totals.paid,0);
  const expenses=allExpenses.filter(e=>{
    const settled=e.totals.state==='paid';
    if(expenseView==='paid'?!settled:settled)return false;
    if(expenseCat!=='all'&&e.category!==expenseCat)return false;
    if(!searchText(`${e.description} ${e.supplier||''} ${e.notes||''} ${(e.installments||[]).map(p=>p.label).join(' ')}`).includes(searchText(expenseSearch)))return false;
    if(expenseStatus==='overdue'&&!e.totals.overdue)return false;
    if(expenseStatus==='partial'&&!(e.totals.paid>0&&e.totals.balance>0))return false;
    if(expenseStatus==='unpaid'&&e.totals.paid>0)return false;
    if(expensePeriod==='all')return true;
    const payments=(e.installments||[]).filter(p=>settled?Number(p.paidAmount)>0:installmentBalance(p)>0);
    return payments.some(p=>matchesPeriod(settled?p.paidAt:p.due,expensePeriod,currentDay))||(expensePeriod==='undated'&&(e.totals.unallocated>0||!payments.length));
  }).sort((a,b)=>{
    const date=e=>(e.installments||[]).filter(p=>expenseView==='paid'?Number(p.paidAmount)>0:installmentBalance(p)>0).map(p=>(expenseView==='paid'?p.paidAt:p.due)||'9999').sort()[0]||'9999';
    return expenseSort==='balance'?b.totals.balance-a.totals.balance:expenseSort==='name'?a.description.localeCompare(b.description,'pt-BR'):expenseSort==='value'?b.totals.planned-a.totals.planned:date(a).localeCompare(date(b));
  });
  const clearTasks=()=>{setTaskSearch('');setTaskCat('all');setTaskOwner('all');setTaskPeriod('all');setTaskStatus('all')};
  const clearExpenses=()=>{setExpenseSearch('');setExpenseCat('all');setExpensePeriod('all');setExpenseStatus('all')};
  const focusPanel=ref=>requestAnimationFrame(()=>{ref.current?.scrollIntoView({behavior:'smooth',block:'start'});ref.current?.focus({preventScroll:true})});
  const filterAlert=(type,period)=>{
    if(type==='task'){setTaskSection('checklist');clearTasks();setTaskView('open');setTaskPeriod(period);setTaskFiltersOpen(true);focusPanel(taskPanel)}
    else{setFinanceSection('services');clearExpenses();setExpenseView('open');setExpensePeriod(period);setExpenseFiltersOpen(true);focusPanel(expensePanel)}
  };
  const taskFilterCount=[taskCat!=='all',taskOwner!=='all',taskPeriod!=='all',taskStatus!=='all'].filter(Boolean).length;
  const expenseFilterCount=[expenseCat!=='all',expensePeriod!=='all',expenseStatus!=='all'].filter(Boolean).length;
  const taskFiltersActive=taskSearch||taskCat!=='all'||taskOwner!=='all'||taskPeriod!=='all'||taskStatus!=='all';
  const expenseFiltersActive=expenseSearch||expenseCat!=='all'||expensePeriod!=='all'||expenseStatus!=='all';
  const toggle=t=>setData(d=>togglePlanningTask(d,t.id,today()));
  const toggleStep=(taskId,stepId)=>setData(d=>togglePlanningSubtask(d,taskId,stepId));
  const saveTask=f=>{setData(d=>({...d,tasks:f.id?d.tasks.map(x=>x.id===f.id?f:x):[{...f,id:id(),status:'todo',completedAt:''},...d.tasks]}));setModal(null)};
  const updateDocumentExpense=(expense,revision)=>{acceptExpense(expense,revision);setModal(m=>m?.type==='documents'&&m.item.id===expense.id?{...m,item:expense}:m)};
  const moveToTrash=(type,itemId)=>{try{setData(trashPlanningItem(data,type,itemId,id));setModal(null)}catch(err){alert(err.message)}};
  const saveExpense=f=>{const {totals,linkedActionIds,...expense}=f;const saved={...expense,id:expense.id||id()};try{setData(d=>modal?.quoteId?contractPlanningQuote(d,modal.quoteId,modal.proposalId,saved,linkedActionIds):saveExpenseWithActions(d,saved,linkedActionIds));setModal(null);if(modal?.quoteId)setFinanceSection('services')}catch(error){alert(error.message)}};
  const alerts=[
    {type:'task',period:'overdue',tone:'overdue',count:summary.overdueTasks,value:`${summary.overdueTasks} ação${summary.overdueTasks===1?'':'s'}`,label:summary.overdueTasks===1?'atrasada':'atrasadas'},
    {type:'task',period:'next7',tone:'soon',count:summary.soonTasks,value:`${summary.soonTasks} ação${summary.soonTasks===1?'':'s'}`,label:summary.soonTasks===1?'vence em até 7 dias':'vencem em até 7 dias'},
    {type:'expense',period:'overdue',tone:'overdue',count:summary.overduePayments,value:money(summary.overdueValue),label:`vencidos · ${summary.overduePayments} pagamento(s)`},
    {type:'expense',period:'next7',tone:'soon',count:summary.soonPayments,value:money(summary.soonValue),label:`em até 7 dias · ${summary.soonPayments} pagamento(s)`}
  ];
  return <>
    <div className="planningIntro"><span className="eyebrow">PLANEJAMENTO DO EVENTO</span><h2>Organização do Chá do Oliver</h2><p>Ações, pagamentos e prazos para acompanhar até o dia do chá.</p><small className={'planningSync '+sync}>{sync==='loading'?'Carregando planejamento…':sync==='saving'?'Salvando…':sync==='synced'?'✓ Sincronizado entre dispositivos':sync==='conflict'?'⚠ Edições simultâneas — escolha qual versão manter':'⚠ Offline — alterações salvas neste dispositivo'}</small>{sync==='offline'&&<button type="button" onClick={retry}>Tentar sincronizar</button>}</div>
    {conflict&&<ConflictReview conflict={conflict} onResolve={resolve}/>}
    <details className="planningAttention"><summary>Precisa da sua atenção <span>{summary.overdueTasks+summary.soonTasks} ações · {money(summary.overdueValue+summary.soonValue)} em pagamentos <small>Ver pendências</small></span></summary><p>Selecione um alerta para consultar as pendências. Os valores mostram o saldo das parcelas.</p><div className="planningAlertGrid">{alerts.map(a=><button key={a.type+a.period} type="button" disabled={!a.count} className={'planningAlertButton '+(a.count?a.tone:'clear')} onClick={()=>filterAlert(a.type,a.period)}><strong>{a.value}</strong><span>{a.label}</span>{a.count>0&&<small>Ver pendências →</small>}</button>)}</div>{!alerts.some(a=>a.count>0)&&<p className="planningAllClear">Tudo em dia: nenhuma pendência vencida ou nos próximos 7 dias.</p>}</details>
    <div className="planningSummary"><div><span>AÇÕES REALIZADAS</span><strong>{taskCounts.done}/{data.tasks.length}</strong><small>{taskCounts.open} a realizar</small></div><div><span>CONTRATADO</span><strong>{money(summary.planned)}</strong><small>total dos gastos</small></div><div><span>PAGO</span><strong>{money(summary.paid)}</strong><small>pagamentos realizados</small></div><div><span>A QUITAR</span><strong>{money(summary.open)}</strong><small>saldo dos serviços</small></div></div>
    <div className="planningColumns" inert={conflict||sync==='loading'?true:undefined}>
      <section className="planningPanel" ref={taskPanel} tabIndex={-1} aria-label="Ações do planejamento">
        <div className="planningPanelHead"><div><span className="eyebrow">AÇÕES</span><h3>Organização</h3></div><button type="button" onClick={()=>setModal(taskSection==='schedule'?{type:'task',initialSchedule:true,initialDate:'2026-12-04'}:{type:'task'})}>{taskSection==='schedule'?'+ Novo horário':'+ Nova tarefa'}</button></div>
        <PlanningTabs id="planning-actions" label="Funções de Ações" value={taskSection} onChange={setTaskSection} options={[["checklist","Checklist"],["schedule","Cronograma"]]}/>
        <div role="tabpanel" id="planning-actions-panel" aria-labelledby={'planning-actions-'+taskSection}>
        {taskSection==='schedule'?<EventSchedule tasks={data.tasks} onAdd={date=>setModal({type:'task',initialSchedule:true,initialDate:date})} onEdit={item=>setModal({type:'task',item})} onToggle={toggle}/>:<>

        <div className="filterPills planningViewSwitch" aria-label="Situação das ações">{[['open','A realizar'],['done','Realizadas']].map(([view,label])=><button key={view} type="button" aria-pressed={taskView===view} className={taskView===view?'active':''} onClick={()=>{setTaskView(view);setTaskSort(view==='done'?'completed':'due');setTaskStatus('all');setTaskPeriod('all')}}>{label} · {taskCounts[view]}</button>)}</div>
        <FilterToolbar search={taskSearch} onSearch={setTaskSearch} placeholder="Tarefa, responsável ou observação" open={taskFiltersOpen} onToggle={()=>setTaskFiltersOpen(x=>!x)} count={taskFilterCount} sort={taskSort} onSort={setTaskSort} sortLabel="Ordenar ações" filterId="planning-task-filters" options={[["due","Prazo"],["priority","Prioridade"],["title","Nome"],...(taskView==='done'?[["completed","Conclusão (recentes)"]]:[])]}/>
        {taskFiltersOpen&&<div id="planning-task-filters" className="planningFilters planningFiltersV2">
          <label>Categoria<select aria-label="Categoria" value={taskCat} onChange={e=>setTaskCat(e.target.value)}><option value="all">Todas as categorias</option>{CATS.map(x=><option key={x}>{x}</option>)}</select></label>
          <label>Responsável<select aria-label="Responsável" value={taskOwner} onChange={e=>setTaskOwner(e.target.value)}><option value="all">Todos os responsáveis</option><option value="unassigned">Sem responsável</option>{owners.map(x=><option key={x}>{x}</option>)}</select></label>
          <PeriodFilter value={taskPeriod} onChange={setTaskPeriod} label="Período do prazo"/>
          <label>Status<select aria-label="Status" value={taskStatus} onChange={e=>setTaskStatus(e.target.value)}><option value="all">{taskView==='open'?'Todas a realizar':'Todas realizadas'}</option>{taskView==='open'&&<><option value="overdue">Atrasadas</option><option value="blocked">Bloqueadas por dependência</option></>}<option value="undated">Sem prazo</option></select></label>
        </div>}
        <div className="planningFilterMeta"><span aria-live="polite">{tasks.length} de {taskCounts[taskView]} ações</span>{taskFiltersActive&&<button type="button" className="planningClear" onClick={clearTasks}>Limpar filtros</button>}</div>
        <div className="taskList">{tasks.map(t=><article className={'taskItem '+(t.status==='done'?'done':'')} key={t.id}><button type="button" className="taskCheck" aria-label={`${t.status==='done'?'Reabrir':'Concluir'} ${t.title}`} aria-pressed={t.status==='done'} disabled={t.status!=='done'&&(taskProgress(t).pending||taskDependencies(t,data.tasks).length>0)} title={t.status!=='done'&&taskDependencies(t,data.tasks).length?'Conclua as dependências primeiro':t.status!=='done'&&taskProgress(t).pending?'Conclua as etapas primeiro':undefined} onClick={()=>toggle(t)}>{t.status==='done'?'✓':''}</button><div><b>{t.title}</b><span>{t.category} · {t.responsible||'Sem responsável'}{t.due?' · '+fmt(t.due):''}</span>{t.expenseId&&(()=>{const linked=data.expenses.find(e=>e.id===t.expenseId);if(!linked)return <span>Serviço vinculado indisponível</span>;const financial=expenseTotals(linked,currentDay);return <button type="button" className="planningTaskExpense" aria-label={`Abrir serviço ${linked.description} de ${t.title}`} onClick={()=>setModal({type:'expense',item:linked})}>{linked.description} · {financial.state==='paid'?'Quitado':'Saldo '+money(financial.balance)}</button>})()}{t.status==='done'?<span>Realizada{t.completedAt?' em '+fmt(t.completedAt):''}</span>:<DueBadge date={t.due} currentDay={currentDay}/>}<TaskDependencies task={t} tasks={data.tasks} onEdit={item=>setModal({type:'task',item})}/><TaskSteps task={t} onToggle={toggleStep}/></div><em className={'priority '+t.priority}>{t.priority==='high'?'Alta':t.priority==='medium'?'Média':'Baixa'}</em><div className="planningRecordActions"><button type="button" className="iconAction" aria-label={`Editar tarefa ${t.title}`} onClick={()=>setModal({type:'task',item:t})}>Editar</button><button type="button" className="iconAction" disabled={data.tasks.length>=500} aria-label={`Duplicar tarefa ${t.title}`} onClick={()=>setModal({type:'task',item:duplicatePlanningTask(t,id)})}>Duplicar</button></div></article>)}{!tasks.length&&<div className="planningEmpty">Nenhuma ação neste filtro.{taskFiltersActive?' Limpe os filtros para ampliar a consulta.':''}</div>}</div>
        </>}
        </div>
      </section>
      <section className="planningPanel" ref={expensePanel} tabIndex={-1} aria-label="Financeiro do planejamento">
        <div className="planningPanelHead"><div><span className="eyebrow">FINANCEIRO</span><h3>Gestão financeira</h3></div>{financeSection==='services'&&<button type="button" onClick={()=>setModal({type:'expense'})}>+ Novo gasto</button>}{financeSection==='quotes'&&<button type="button" disabled={data.quotes.length>=500} onClick={()=>setModal({type:'quote'})}>+ Nova cotação</button>}</div>
        <PlanningTabs id="planning-finance" label="Funções do Financeiro" value={financeSection} onChange={setFinanceSection} options={[["services","Serviços"],["payments","Pagamentos"],["quotes","Cotações"],["analysis","Análise"]]}/>
        <div role="tabpanel" id="planning-finance-panel" aria-labelledby={'planning-finance-'+financeSection}>
        {financeSection==='payments'?<UpcomingPayments expenses={data.expenses} currentDay={currentDay} onEdit={item=>setModal({type:'expense',item})} onPay={(item,installmentId)=>setModal({type:'payment',item,installmentId})}/>:financeSection==='analysis'?<><CostPerGuest expenses={data.expenses} settings={data.guestSettings} onChange={guestSettings=>setData(d=>({...d,guestSettings}))}/><BudgetOverview expenses={data.expenses} budgets={data.budgets} onEdit={()=>setModal({type:'budget'})}/></>:financeSection==='quotes'?<QuoteBoard quotes={data.quotes} expenses={data.expenses} trash={data.trash} currentDay={currentDay} onEdit={item=>setModal({type:'quote',item})} onOpenExpense={item=>{setFinanceSection('services');setModal({type:'expense',item})}} onContract={(quote,proposal)=>setModal({type:'expense',quoteId:quote.id,proposalId:proposal.id,item:{description:quote.title,category:quote.category,supplier:proposal.supplier,contracted:proposal.amount,notes:[proposal.terms,proposal.contact?'Contato: '+proposal.contact:'',proposal.validUntil?'Proposta válida até '+fmt(proposal.validUntil):'',proposal.notes].filter(Boolean).join('\n'),installments:[]}})}/>:<>

        <div className="filterPills planningViewSwitch" aria-label="Situação dos serviços">{[['open','A quitar',summary.open],['paid','Quitados',settledValue]].map(([view,label,value])=><button key={view} type="button" aria-pressed={expenseView===view} className={expenseView===view?'active':''} onClick={()=>{setExpenseView(view);setExpenseStatus('all');setExpensePeriod('all')}}>{label} · {expenseCounts[view]} · {money(value)}</button>)}</div>
        <FilterToolbar search={expenseSearch} onSearch={setExpenseSearch} placeholder="Gasto, fornecedor ou parcela" open={expenseFiltersOpen} onToggle={()=>setExpenseFiltersOpen(x=>!x)} count={expenseFilterCount} sort={expenseSort} onSort={setExpenseSort} sortLabel="Ordenar gastos" filterId="planning-expense-filters" options={[["due","Vencimento"],["balance","Maior saldo"],["name","Nome"],["value","Maior valor contratado"]]}/>
        {expenseFiltersOpen&&<div id="planning-expense-filters" className="planningFilters planningFiltersV2">
          <label>Categoria<select aria-label="Categoria" value={expenseCat} onChange={e=>setExpenseCat(e.target.value)}><option value="all">Todas as categorias</option>{CATS.map(x=><option key={x}>{x}</option>)}</select></label>
          <PeriodFilter value={expensePeriod} onChange={setExpensePeriod} paid={expenseView==='paid'} label={expenseView==='paid'?'Data do pagamento':'Período do vencimento'}/>
          {expenseView==='open'&&<label>Status do serviço<select aria-label="Status do serviço" value={expenseStatus} onChange={e=>setExpenseStatus(e.target.value)}><option value="all">Todos os status</option><option value="unpaid">Sem pagamento</option><option value="partial">Parcialmente pago</option><option value="overdue">Com parcela vencida</option></select></label>}
        </div>}
        <div className="planningFilterMeta"><span aria-live="polite">{expenses.length} de {expenseCounts[expenseView]} serviço(s)</span>{expenseFiltersActive&&<button type="button" className="planningClear" onClick={clearExpenses}>Limpar filtros</button>}</div>
        <div className="expenseList">{expenses.map(e=>{
          const next=(e.installments||[]).filter(p=>installmentBalance(p)>0&&p.due).sort((a,b)=>a.due.localeCompare(b.due))[0];
          const percent=e.totals.planned>0?Math.min(100,Math.round(e.totals.paid/e.totals.planned*100)):0;
          return <article className="planningExpenseCard" key={e.id}>
            <div className="planningExpenseHead"><div><b>{e.description}</b><span>{e.category}{e.supplier?' · '+e.supplier:''}</span><span className={'expenseStatus '+(e.totals.state==='paid'?'paid':e.totals.overdue?'overdue':'open')}>{e.totals.state==='paid'?'Quitado':e.totals.planned>0?'A quitar':'Valor a definir'}</span></div><div className="planningRecordActions"><button type="button" className="iconAction" aria-label={`Editar gasto ${e.description}`} onClick={()=>setModal({type:'expense',item:e})}>Editar</button><button type="button" className="iconAction" disabled={data.expenses.length>=500} aria-label={`Duplicar gasto ${e.description}`} onClick={()=>setModal({type:'expense',item:duplicatePlanningExpense(e)})}>Duplicar</button></div></div>
            <div className="planningExpenseNumbers"><div><small>Contratado</small><strong>{money(e.totals.planned)}</strong></div><div><small>Pago</small><strong>{money(e.totals.paid)}</strong></div><div><small>Saldo a quitar</small><strong>{money(e.totals.balance)}</strong></div></div>
            {e.totals.planned>0&&<div className="planningPaidProgress"><progress max="100" value={percent} aria-label={`Percentual pago de ${e.description}`}/><span>{percent}% pago</span></div>}
            {next&&<div className="planningNextPayment"><span>{next.label||'Próxima parcela'} · {fmt(next.due)}</span><DueBadge date={next.due} currentDay={currentDay}/></div>}
            {e.totals.unallocated>0&&<p className="planningUnallocated">{money(e.totals.unallocated)} ainda sem programação <button type="button" onClick={()=>setModal({type:'expense',item:e})}>Programar</button></p>}
            {e.totals.balance>0&&<button type="button" className="planningRegisterPayment" aria-label={`Registrar pagamento de ${e.description}`} onClick={()=>setModal({type:'payment',item:e})}>Registrar pagamento</button>}
            <button type="button" className="planningDocumentsButton" aria-label={`Documentos de ${e.description}`} onClick={()=>setModal({type:'documents',item:e})}>Documentos · {(e.attachments||[]).length}</button>
            <details className="planningPaymentDetails"><summary>Ver pagamentos · {(e.installments||[]).length}</summary><div className="planningPayments">
              {!(e.installments||[]).length&&<p className="planningEmpty">Nenhum pagamento programado. Edite o serviço para cadastrar parcelas.</p>}
              {(e.installments||[]).map((p,i)=>{
                const balance=installmentBalance(p),settled=balance===0&&Number(p.amount)>0;
                return <div className="planningPayment" key={p.id||i}><div><b>{p.label||'Pagamento'}</b><span>{settled?(p.paidAt?'Pago em '+fmt(p.paidAt):'Data de pagamento não informada'):(p.due?'Vencimento '+fmt(p.due):'Sem vencimento')}{settled?' · '+(p.payment||'Não informado'):''}</span>
                  {settled?<span className="expenseStatus paid">Quitado</span>:<><span className={'expenseStatus '+(Number(p.paidAmount)>0?'partial':'open')}>{Number(p.paidAmount)>0?'Pagamento parcial':'A quitar'}</span>{balance>0&&<DueBadge date={p.due} currentDay={currentDay}/>}</>}
                  {paymentHistory(p).length>0&&<ul className="planningPaymentHistory" aria-label={`Histórico de ${p.label||'pagamento'}`}>{paymentHistory(p).map(h=><li key={h.id} className={h.reversedAt?'reversed':''}>
                    <span>{money(h.amount)} · {h.paidAt?fmt(h.paidAt):'Data não informada'} · {h.payment||'Outros'}</span>
                    {h.reversedAt?<small>Estornado · {fmt(eventToday(new Date(h.reversedAt)))} · {h.reversalReason}</small>:<div className="planningHistoryActions"><button type="button" aria-label={`Editar pagamento ${h.id}`} onClick={()=>setModal({type:'revision',item:e,installmentId:p.id,paymentId:h.id,action:'edit'})}>Editar</button><button type="button" aria-label={`Estornar pagamento ${h.id}`} onClick={()=>setModal({type:'revision',item:e,installmentId:p.id,paymentId:h.id,action:'reverse'})}>Estornar</button></div>}
                    <button type="button" className="planningReceiptButton" aria-label={`Comprovantes do pagamento ${h.id}`} onClick={()=>setModal({type:'documents',item:e,installmentId:p.id,paymentId:h.id})}>Comprovantes · {(h.attachments||[]).length}</button>{h.changes?.length>0&&<details className="planningPaymentChanges"><summary>Correções · {h.changes.length}</summary>{h.changes.map((change,j)=><small key={j}>Anterior: {money(change.amount)} · {change.paidAt?fmt(change.paidAt):'Data não informada'} · {change.payment} · {change.reason||'Correção do lançamento'}</small>)}</details>}
                  </li>)}</ul>}

                </div><div className="planningPaymentValue"><strong>{money(settled?p.paidAmount:balance)}</strong><small>{settled?'valor pago':'saldo a quitar'}{!settled&&Number(p.paidAmount)>0?' · '+money(p.paidAmount)+' já pagos':''}</small></div></div>;
              })}
            </div></details>
          </article>;
        })}{!expenses.length&&<div className="planningEmpty">Nenhum serviço neste filtro.{expenseFiltersActive?' Limpe os filtros para ampliar a consulta.':''}</div>}</div>
        </>}
        </div>
      </section>
    </div>
    <footer className="planningFooter"><button type="button" onClick={()=>setModal({type:'history'})}>Histórico do planejamento</button><button type="button" className="planningExport" onClick={()=>setModal({type:'export'})}>Exportar planejamento</button><button type="button" className="planningTrashButton" disabled={!!conflict||sync==='loading'} onClick={()=>setModal({type:'trash'})}>Lixeira · {data.trash.length}</button></footer>
    {modal&&!conflict&&<Modal guard={['task','expense','quote','budget','payment','revision'].includes(modal.type)} side={['task','expense'].includes(modal.type)} busy={!!modal.busy} onClose={()=>{if(!modal.busy)setModal(null)}}>{modal.type==='history'?<PlanningHistory entries={data.history} onClose={()=>setModal(null)}/>:modal.type==='trash'?<TrashForm entries={data.trash} onRestore={entryId=>{const next=restorePlanningItem(data,entryId);setData(next)}} onClose={()=>setModal(null)}/>:modal.type==='documents'?<AttachmentManager item={modal.item} installmentId={modal.installmentId} paymentId={modal.paymentId} onChange={updateDocumentExpense} onBusy={busy=>setModal(m=>m?.type==='documents'?{...m,busy}:m)} sync={sync} documentApi={documentApi} onClose={()=>setModal(null)}/>:modal.type==='export'?<ExportPlanningForm data={data} currentDay={currentDay} onClose={()=>setModal(null)}/>:modal.type==='quote'?<QuoteForm item={modal.item} categories={CATS} onClose={()=>setModal(null)} onDelete={()=>{if(confirm('Mover esta cotação para a lixeira?'))moveToTrash('quote',modal.item.id)}} onSave={quote=>{setData(d=>({...d,quotes:quote.id?d.quotes.map(q=>q.id===quote.id?quote:q):[{...quote,id:id()},...d.quotes]}));setModal(null)}}/>:modal.type==='budget'?<BudgetForm budgets={data.budgets} onSave={budgets=>{setData(d=>({...d,budgets}));setModal(null)}} onClose={()=>setModal(null)}/>:modal.type==='task'?<TaskForm tasks={data.tasks} item={modal.item||(modal.initialSchedule?{eventDate:modal.initialDate}:undefined)} initialSchedule={modal.initialSchedule} expenses={data.expenses} onClose={()=>setModal(null)} onSave={saveTask} onDelete={()=>{if(confirm('Mover esta tarefa para a lixeira?')){moveToTrash('task',modal.item.id)}}}/>:modal.type==='revision'?<PaymentRevisionForm item={modal.item} installmentId={modal.installmentId} paymentId={modal.paymentId} action={modal.action} onSave={saveExpense} onClose={()=>setModal(null)}/>:modal.type==='payment'?<PaymentForm item={modal.item} initialInstallmentId={modal.installmentId} onSave={saveExpense} onClose={()=>setModal(null)}/>:<ExpenseForm item={modal.item} tasks={data.tasks} linkedTasks={modal.item?data.tasks.filter(t=>t.expenseId===modal.item.id):[]} onClose={()=>setModal(null)} onSave={saveExpense} onDelete={()=>{if(confirm('Mover este gasto e seus pagamentos para a lixeira?')){moveToTrash('expense',modal.item.id)}}}/>}</Modal>}
  </>;
}
let mounted=false;function mount(){if(mounted)return;const host=document.querySelector('.planningOverview');if(!host)return;mounted=true;host.innerHTML='';createRoot(host).render(<Planning/>)}document.addEventListener('admin-sections-ready',mount);window.addEventListener('pageshow',mount);new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});setTimeout(mount,100);
