/* Navegação por abas do painel — Chá do Oliver */
(function(){
 let active=sessionStorage.getItem('oliverAdminTab')||'overview',scheduled=false,applying=false;
 const defs=[['overview','Visão geral'],['guests','Convidados'],['pending','Pendências'],['diapers','Fraldas'],['management','Gestão']];
 const selectors={overview:['.eventCentral','.dashboard'],guests:['.adminManagerBar','.adminAdd','.adminError','.confirmationFilter','.adminTools','.guestList'],pending:['.eventOperations'],diapers:['.diaperManagement'],management:['.giftDashboard','.adminActivity','.activitySection']};
 function ensureTabs(){const heading=document.querySelector('.adminHeading');if(!heading)return null;let nav=document.querySelector('.adminTabs');if(!nav){nav=document.createElement('nav');nav.className='adminTabs';nav.setAttribute('aria-label','Seções do painel');nav.innerHTML=defs.map(([k,l])=>`<button type="button" data-admin-tab="${k}">${l}</button>`).join('');heading.insertAdjacentElement('afterend',nav);nav.addEventListener('click',e=>{const b=e.target.closest('[data-admin-tab]');if(!b)return;active=b.dataset.adminTab;sessionStorage.setItem('oliverAdminTab',active);apply();});}return nav;}
 function apply(){scheduled=false;if(applying)return;applying=true;const nav=ensureTabs();if(!nav){applying=false;return;}nav.querySelectorAll('[data-admin-tab]').forEach(b=>{const on=b.dataset.adminTab===active;b.classList.toggle('active',on);b.setAttribute('aria-selected',on?'true':'false');});Object.entries(selectors).forEach(([tab,list])=>list.forEach(sel=>document.querySelectorAll(sel).forEach(el=>{el.classList.add('adminTabbedBlock');el.classList.toggle('adminTabHidden',tab!==active);})));if(active==='management'&&!document.querySelector('.giftDashboard,.adminActivity,.activitySection')){active='overview';sessionStorage.setItem('oliverAdminTab',active);}applying=false;}
 function schedule(){if(scheduled||applying)return;scheduled=true;requestAnimationFrame(apply);}
 const ob=new MutationObserver(m=>{if(applying)return;if(m.some(x=>[...x.addedNodes,...x.removedNodes].some(n=>n.nodeType===1&&!n.closest?.('.adminTabs'))))schedule();});ob.observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('admin-sections-ready',schedule);schedule();
})();