import React,{useEffect,useRef,useState} from 'react';
import {expenseTotals,confirmedGuestCounts,guestCostAnalysis,quoteComparison} from './planning-utils.mjs';
const money=value=>(Number(value)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=date=>date?new Date(date+'T12:00:00').toLocaleDateString('pt-BR'):'';
const id=()=>crypto.randomUUID();
export function PlanningTabs({id:prefix,label,value,onChange,options}) {
  const ref=useRef(null);
  const navigate=event=>{const index=options.findIndex(([key])=>key===value);let next;
    if(event.key==='ArrowRight')next=(index+1)%options.length;else if(event.key==='ArrowLeft')next=(index-1+options.length)%options.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=options.length-1;else return;
    event.preventDefault();onChange(options[next][0]);ref.current?.querySelectorAll('[role=tab]')[next]?.focus();
  };
  return <div className="planningFunctionTabs" role="tablist" aria-label={label} ref={ref} onKeyDown={navigate}>{options.map(([key,text])=><button key={key} type="button" role="tab" id={prefix+'-'+key} aria-controls={prefix+'-panel'} aria-selected={value===key} tabIndex={value===key?0:-1} onClick={()=>onChange(key)}>{text}</button>)}</div>;
}
export function QuoteForm({item,categories,onSave,onClose,onDelete}) {
  const[f,setF]=useState(item?structuredClone(item):{title:'',category:'Outros',proposals:[{id:id(),supplier:'',amount:'',terms:'',validUntil:'',contact:'',notes:''}]}),[active,setActive]=useState(0),[error,setError]=useState('');
  const proposal=f.proposals[active];
  const change=(key,value)=>{setF(x=>({...x,proposals:x.proposals.map((p,i)=>i===active?{...p,[key]:value}:p)}));setError('')};
  const submit=event=>{event.preventDefault();const invalid=f.proposals.findIndex(p=>!p.supplier.trim()||p.amount===''||!Number.isFinite(Number(p.amount))||Number(p.amount)<0||Number(p.amount)>999999999);
    if(invalid>=0){setActive(invalid);setError('Informe o fornecedor e um valor válido em todas as propostas.');return}
    if(!f.title.trim()){setError('Informe o serviço que deseja cotar.');return}
    onSave({...f,title:f.title.trim(),proposals:f.proposals.map(p=>({...p,supplier:p.supplier.trim(),amount:Math.round(Number(p.amount)*100)/100}))});
  };
  return <form onSubmit={submit}><h3>{item?'Editar':'Nova'} cotação</h3><p className="planningFormHint">Compare propostas para o mesmo serviço. Uma cotação só entra nos gastos depois de contratada.</p><div className="formGrid"><label>Serviço em cotação<input autoFocus required maxLength="180" value={f.title} onChange={e=>setF(x=>({...x,title:e.target.value}))}/></label><label>Categoria da cotação<select value={f.category} onChange={e=>setF(x=>({...x,category:e.target.value}))}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div>
    <div className="planningQuoteEditor"><div className="planningQuoteEditorHead"><label>Proposta em edição<select value={active} onChange={e=>setActive(Number(e.target.value))}>{f.proposals.map((p,i)=><option key={p.id} value={i}>{p.supplier||`Fornecedor ${i+1}`}</option>)}</select></label><button type="button" disabled={f.proposals.length>=20} onClick={()=>{setF(x=>({...x,proposals:[...x.proposals,{id:id(),supplier:'',amount:'',terms:'',validUntil:'',contact:'',notes:''}]}));setActive(f.proposals.length)}}>+ Adicionar proposta</button></div>
      <div className="formGrid"><label>Fornecedor da proposta<input required maxLength="180" value={proposal.supplier} onChange={e=>change('supplier',e.target.value)}/></label><label>Valor da proposta<input required type="number" min="0" max="999999999" step="0.01" value={proposal.amount} onChange={e=>change('amount',e.target.value)}/></label><label>Validade da proposta<input type="date" value={proposal.validUntil||''} onChange={e=>change('validUntil',e.target.value)}/></label><label>Contato do fornecedor<input type="tel" maxLength="180" value={proposal.contact||''} onChange={e=>change('contact',e.target.value)}/></label></div><label>Condições e itens inclusos<textarea maxLength="4000" value={proposal.terms||''} onChange={e=>change('terms',e.target.value)} placeholder="Ex.: sinal de 30%, entrega e montagem inclusas"/></label><label>Observações da proposta<textarea maxLength="4000" value={proposal.notes||''} onChange={e=>change('notes',e.target.value)}/></label>{f.proposals.length>1&&<button type="button" className="danger" onClick={()=>{setF(x=>({...x,proposals:x.proposals.filter((_,i)=>i!==active)}));setActive(0);setError('')}}>Remover esta proposta</button>}
    </div>{error&&<p role="alert" className="error">{error}</p>}<div className="modalActions">{item&&<button type="button" className="danger" onClick={onDelete}>Excluir cotação</button>}<button type="button" onClick={onClose}>Cancelar</button><button type="submit" className="primary">Salvar cotação</button></div></form>;
}
export function QuoteBoard({quotes,expenses,trash,currentDay,onEdit,onContract,onOpenExpense}) {
  const[selected,setSelected]=useState('');const quote=quotes.find(q=>q.id===selected);
  if(!quote)return <section className="planningQuoteBoard" aria-label="Cotações de fornecedores"><div className="planningSubviewHeading"><h4>Cotações de fornecedores</h4><span>{quotes.length} serviço(s) em comparação</span></div><p className="planningFormHint">Compare preço, condições e validade antes de contratar. Estes valores não entram no total contratado.</p>{quotes.length?<div className="planningQuoteIndex">{quotes.map(q=><button type="button" key={q.id} onClick={()=>setSelected(q.id)}><span><b>{q.title}</b><small>{q.category} · {q.proposals.length} proposta(s){q.expenseId?' · Contratada':''}</small></span><span>Comparar →</span></button>)}</div>:<div className="planningEmpty">Nenhuma cotação cadastrada. Use “Nova cotação” para comparar fornecedores.</div>}</section>;
  const comparison=quoteComparison(quote,currentDay),expense=expenses.find(e=>e.id===quote.expenseId),archived=(trash||[]).some(t=>t.type==='expense'&&t.item.id===quote.expenseId);
  return <section className="planningQuoteBoard" aria-label="Comparação de fornecedores"><button type="button" className="planningBack" onClick={()=>setSelected('')}>← Todas as cotações</button><div className="planningSubviewHeading"><h4>{quote.title}</h4>{!quote.expenseId&&<button type="button" onClick={()=>onEdit(quote)}>Editar cotação</button>}</div><p className="planningFormHint">{quote.category} · {quote.proposals.length} propostas. Confira os itens inclusos e as condições; o menor valor pode ter uma cobertura diferente.</p>{quote.expenseId&&<p className="planningQuoteChosen">{expense?'Proposta contratada. Os pagamentos são controlados em Serviços.':archived?'O serviço contratado está na lixeira. Restaure-o para retomar os pagamentos.':'O serviço contratado não está disponível.'}{expense&&<button type="button" onClick={()=>onOpenExpense(expense)}>Abrir serviço contratado</button>}</p>}
    <div className="planningQuoteComparisons">{comparison.map(p=><article key={p.id} className={quote.selectedProposalId===p.id?'selected':''}><div className="planningQuotePrice"><b>{p.supplier}</b><strong>{money(p.amount)}</strong></div><div className="planningQuoteBadges">{p.lowest&&<span>Menor valor</span>}{quote.selectedProposalId===p.id&&<span>Contratada</span>}{p.expired&&<span className="expired">Validade encerrada</span>}</div>{p.validUntil&&<p>Válida até {fmt(p.validUntil)}</p>}{p.contact&&<p>Contato: {p.contact}</p>}<p className="planningQuoteTerms">{p.terms||'Condições não informadas.'}</p>{p.notes&&<p className="planningQuoteTerms">{p.notes}</p>}{!quote.expenseId&&<button type="button" onClick={()=>onContract(quote,p)} aria-label={`Contratar proposta de ${p.supplier}`}>Contratar esta proposta</button>}</article>)}</div>
  </section>;
}
function readGuests(){try{const cache=JSON.parse(sessionStorage.getItem('oliverAdminListCache')||'null');return Array.isArray(cache?.data?.families)?{families:cache.data.families,at:cache.at}:null}catch{return null}}
export function CostPerGuest({expenses,settings,onChange}) {
  const[guests,setGuests]=useState(readGuests);
  useEffect(()=>{const update=event=>setGuests(event.detail);window.addEventListener('oliver-admin-guests',update);return()=>window.removeEventListener('oliver-admin-guests',update)},[]);
  const config={basis:'confirmed',excludeUnder5:true,estimatedGuests:100,...settings},counts=guests?confirmedGuestCounts(guests.families):null;
  const analysis=guestCostAnalysis(expenses,counts,config);
  return <section className="planningGuestCost" aria-label="Custo por convidado"><div className="planningSubviewHeading"><h4>Custo por convidado</h4><span>Sobre o total contratado</span></div><div className="formGrid"><label>Base do cálculo<select value={config.basis} onChange={e=>onChange({...config,basis:e.target.value})}><option value="confirmed">Convidados confirmados</option><option value="estimate">Estimativa de público</option></select></label>{config.basis==='estimate'?<label>Pessoas estimadas<input aria-label="Pessoas estimadas" type="number" min="1" max="10000" step="1" value={config.estimatedGuests??''} onChange={e=>onChange({...config,estimatedGuests:e.target.value===''?null:Math.min(10000,Math.max(0,Math.trunc(Number(e.target.value))))})}/></label>:<label className="checkLine"><input type="checkbox" checked={config.excludeUnder5} onChange={e=>onChange({...config,excludeUnder5:e.target.checked})}/> Excluir crianças menores de 5 anos</label>}</div>
    <div className="planningCostMetrics"><div><span>CONTRATADO</span><strong>{money(analysis.contracted)}</strong></div><div><span>PESSOAS NA BASE</span><strong>{analysis.people??'—'}</strong></div><div><span>CUSTO POR PESSOA</span><strong>{analysis.perGuest===null?'—':money(analysis.perGuest)}</strong></div></div>
    {config.basis==='confirmed'?<>{counts?<p className="planningFormHint">{counts.adults} adulto(s) · {counts.children} criança(s), sendo {counts.under5} menores de 5. Somente confirmações “Sim”; núcleos de teste são excluídos.{guests.at?' Dados de '+new Date(guests.at).toLocaleString('pt-BR')+'.':''}</p>:<p className="planningFormHint">Aguardando a lista de confirmações do painel. Você também pode usar uma estimativa de público.</p>}{analysis.people===0&&<p className="planningFormHint">Ainda não há convidados confirmados na base escolhida.</p>}</>:<p className="planningFormHint">Simulação para {analysis.people||'—'} pessoas. A estimativa não altera a lista de convidados.</p>}
    <p className="planningFormHint">Cotações não contratadas ficam fora do cálculo. O valor por pessoa é uma média do evento, sem divisão individual de cobrança.</p>
  </section>;
}
