import {taskDependencies} from './planning-utils.mjs';
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function schedulePrintHtml(rows,date,{tasks=rows,scope='Todos os horários do dia'}={}) {
  const day=/^\d{4}-\d{2}-\d{2}$/.test(date)?date.split('-').reverse().join('/'):'Data não informada';
  const text=(label,value)=>value?`<p><strong>${escape(label)}:</strong> ${escape(value)}</p>`:'';
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cronograma - Chá do Oliver - ${escape(day)}</title><style>
  @page{size:A4;margin:14mm}*{box-sizing:border-box}body{margin:0;padding:20px;color:#263021;font:13px/1.4 Arial,sans-serif;background:white}header{margin-bottom:16px}h1{font-size:22px;margin:0 0 6px}header p{margin:3px 0;color:#505849;font-size:12px}.schedule{width:100%;border-collapse:collapse;table-layout:fixed}.check-col{width:36px}.time-col{width:92px}thead{display:table-header-group}th{text-align:left;border-top:2px solid #657442;border-bottom:1px solid #657442;padding:9px 8px;font-size:11px;text-transform:uppercase;letter-spacing:.04em}td{vertical-align:top;padding:12px 8px;border-bottom:1px solid #ccd1c4;overflow-wrap:anywhere}tr{break-inside:avoid;page-break-inside:avoid}.check{padding-top:14px}.checkbox{display:inline-block;width:16px;height:16px;border:1.4px solid #39462e;background:white}.time{font-weight:bold;font-size:13px;white-space:nowrap}.time small{display:block;font-weight:normal;font-size:11px;margin-top:3px}h2{font-size:14px;margin:0 0 5px;line-height:1.35}p{margin:3px 0;white-space:pre-wrap;overflow-wrap:anywhere}.state{font-size:11px;color:#505849}.warning{font-size:11px;font-weight:bold}.steps{list-style:none;padding:0;margin:6px 0}.steps li{margin:3px 0}.step-check{display:inline-block;width:10px;height:10px;border:1px solid #505849;margin-right:5px;vertical-align:baseline;font-size:8px;line-height:8px;text-align:center}footer{margin-top:16px;font-size:11px;color:#505849}@media print{body{padding:0;font-size:9.5pt}h1{font-size:18pt}header p{font-size:9pt}h2{font-size:11pt}.time{font-size:10pt}.time small,.state,.warning{font-size:8.5pt}.check-col{width:10mm}.time-col{width:25mm}.checkbox{width:4mm;height:4mm}th{font-size:8pt;padding:7pt 5pt}td{padding:9pt 5pt}header{break-after:avoid}footer{font-size:8pt}}@media screen and (max-width:480px){body{padding:12px}.check-col{width:27px}.time-col{width:65px}td,th{padding-left:4px;padding-right:4px}h1{font-size:18px}.time{font-size:12px}.time small{font-size:10px}}
  </style></head><body><header><h1>Chá do Oliver · Cronograma</h1><p>${escape(day)} · ${rows.length} ação(ões)</p><p>${escape(scope)}</p><p>Marque o check ao concluir cada ação no dia do evento.</p></header><table class="schedule"><colgroup><col class="check-col"><col class="time-col"><col></colgroup><thead><tr><th aria-label="Check">✓</th><th>Horário</th><th>Ação e orientações</th></tr></thead><tbody>${rows.map(t=>{const dependencies=taskDependencies(t,tasks);return `<tr><td class="check"><span class="checkbox" role="img" aria-label="Check para marcar à mão"></span></td><td class="time">${escape(t.eventTime)}${t.eventEnd?'<small>até '+escape(t.eventEnd)+'</small>':''}</td><td><h2>${escape(t.title)}</h2><p class="state">${t.status==='done'?'Realizada no planejamento':'A realizar'}</p>${text('Responsável',t.responsible||'Sem responsável')}${text('Local',t.place||'Não informado')}${text('Contato',t.contact)}${dependencies.length?`<p class="warning">Dependências pendentes: ${escape(dependencies.map(d=>d.title).join('; '))}</p>`:''}${t.subtasks?.length?`<ul class="steps">${t.subtasks.map(s=>`<li><span class="step-check">${s.done?'✓':''}</span>${escape(s.title)}</li>`).join('')}</ul>`:''}${text('Observação',t.notes)}</td></tr>`}).join('')}</tbody></table><footer>Os checks são para uso no papel e não alteram o planejamento no sistema.</footer></body></html>`;
}
