import React,{useState} from 'react';
import {personalPending,planningResponsibles} from './planning-pending.mjs';
import {deadline,daysUntil} from './planning-utils.mjs';
const types={tasks:'Ação',shopping:'Compra',schedule:'Cronograma'};
const dateLabel=value=>value?value.split('-').reverse().join('/'):'';
export function PersonalPending({data,today,owner,onOwner,onEdit,onClose}) {
  const [type,setType]=useState('all'),[period,setPeriod]=useState('all');
  const rows=personalPending(data,today,{owner,type,period}),all=personalPending(data,today,{owner}),owners=planningResponsibles(data);
  const overdue=all.filter(row=>daysUntil(row.date,today)!==null&&daysUntil(row.date,today)<0).length;
  return <div className="planningPending"><h3>Minhas pendências</h3><p className="planningFormHint">Ações, compras e horários pendentes por responsável. Cada ação aparece uma vez; as que têm horário ficam em Cronograma.</p>
    <label>Responsável das pendências<select aria-label="Responsável das pendências" value={owner} onChange={e=>onOwner(e.target.value)}><option value="__all__">Todos os responsáveis</option><option value="__unassigned__">Sem responsável</option>{owner!=='__all__'&&owner!=='__unassigned__'&&!owners.some(([key])=>key===owner)&&<option value={owner}>Responsável sem cadastros</option>}{owners.map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>
    <p className="planningPendingSummary">{all.length} pendência(s) · {overdue} atrasada(s)</p>
    <details className="planningPendingFilters"><summary>Filtrar pendências{type!=='all'||period!=='all'?' · Ativo':''}</summary><div className="formGrid"><label>Tipo de pendência<select aria-label="Tipo de pendência" value={type} onChange={e=>setType(e.target.value)}><option value="all">Todos</option>{Object.entries(types).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Período das pendências<select aria-label="Período das pendências" value={period} onChange={e=>setPeriod(e.target.value)}>{[['all','Todos'],['overdue','Atrasadas'],['today','Hoje'],['next7','Próximos 7 dias'],['undated','Sem prazo']].map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div></details>
    <div className="planningFilterMeta"><span role="status">{rows.length} de {all.length} pendências</span>{(type!=='all'||period!=='all')&&<button type="button" onClick={()=>{setType('all');setPeriod('all')}}>Limpar filtros</button>}</div>
    <div className="planningPendingList">{rows.map(row=>{const badge=deadline(row.date,today),t=row.item;return <article key={row.key}><div><small>{types[row.type]} · {t.responsible?.trim()||'Sem responsável'}</small><b>{row.title}</b>{row.type==='shopping'?<><span>{Number(t.quantity).toLocaleString('pt-BR')} {t.unit} · {t.status==='ordered'?'Encomendado':'A comprar'}</span>{row.linkedTask&&<span>Ação: {row.linkedTask.title}</span>}{t.taskId&&!row.linkedTask&&<span>Ação vinculada indisponível</span>}{row.date&&<span>Prazo da ação vinculada: {dateLabel(row.date)}</span>}</>:<>{t.due&&<span>Prazo: {dateLabel(t.due)}</span>}{row.type==='schedule'&&<span>{dateLabel(t.eventDate)} · {t.eventTime}{t.eventEnd?' até '+t.eventEnd:''}{t.place?' · '+t.place:''}</span>}{row.blocked&&<span className="planningPendingBlocked">Dependência pendente</span>}</>}<span className={'planningDeadline '+badge.tone}>{badge.label}</span></div><button type="button" aria-label={`Abrir ${types[row.type].toLowerCase()} ${row.title}`} onClick={()=>onEdit(row.type==='shopping'?'shopping':'task',t)}>Abrir</button></article>})}{!rows.length&&<p className="planningEmpty">{all.length?'Nenhuma pendência corresponde aos filtros.':'Nenhuma pendência para este responsável.'}</p>}</div>
    <p className="planningFormHint">Compras usam o prazo ou a data do cronograma da ação vinculada como referência. O responsável da compra é o informado no próprio item.</p>
    <div className="modalActions"><button type="button" onClick={onClose}>Fechar</button></div>
  </div>;
}
