import {taskDependencies} from './planning-utils.mjs';
const escape=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
export function schedulePrintHtml(rows,date,{tasks=rows,scope='Todos os horários do dia'}={}) {
  const day=/^\d{4}-\d{2}-\d{2}$/.test(date)?date.split('-').reverse().join('/'):'Data não informada';
  const text=(label,value)=>value?`<p><strong>${escape(label)}:</strong> ${escape(value)}</p>`:'';
  return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cronograma — Chá do Oliver — ${escape(day)}</title><style>
  @page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;padding:24px;color:#263021;font:14px/1.5 Arial,sans-serif;background:white}header{border-bottom:2px solid #657442;padding-bottom:14px;margin-bottom:20px}h1{font-size:24px;margin:0 0 6px}header p{margin:4px 0;color:#505849}.schedule{list-style:none;padding:0;margin:0}.schedule>li{display:grid;grid-template-columns:110px minmax(0,1fr);gap:16px;border-bottom:1px solid #ccd1c4;padding:16px 0;break-inside:avoid;page-break-inside:avoid}.time{font-weight:bold;font-size:16px}h2{font-size:17px;margin:0 0 5px}p{margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere}ul{padding-left:20px;margin:8px 0}.state{font-size:12px;color:#505849}.warning{font-size:12px;font-weight:bold}footer{margin-top:20px;font-size:11px;color:#505849}@media print{body{padding:0;font-size:11pt}h1{font-size:19pt}h2{font-size:13pt}.time{font-size:12pt}header{break-after:avoid}a{color:inherit}}@media screen and (max-width:480px){body{padding:16px}.schedule>li{grid-template-columns:1fr;gap:6px}}
  </style></head><body><header><h1>Chá do Oliver · Cronograma</h1><p>${escape(day)} · ${rows.length} ação(ões)</p><p>${escape(scope)}</p></header><ol class="schedule">${rows.map(t=>{const dependencies=taskDependencies(t,tasks);return `<li><div class="time">${escape(t.eventTime)}${t.eventEnd?'<br>até '+escape(t.eventEnd):''}</div><div><h2>${escape(t.title)}</h2><p class="state">${t.status==='done'?'Realizada':'A realizar'}</p>${text('Responsável',t.responsible||'Sem responsável')}${text('Local',t.place||'Não informado')}${text('Contato',t.contact)}${dependencies.length?`<p class="warning">Dependências pendentes: ${escape(dependencies.map(d=>d.title).join('; '))}</p>`:''}${t.subtasks?.length?`<ul>${t.subtasks.map(s=>`<li>${s.done?'[OK]':'[ ]'} ${escape(s.title)}</li>`).join('')}</ul>`:''}${text('Observação',t.notes)}</div></li>`}).join('')}</ol><footer>Confira os horários e contatos antes do evento.</footer></body></html>`;
}
