import React,{useMemo,useState,useEffect} from 'react';
import{createRoot}from'react-dom/client';
import{Search,MapPin,CalendarDays,Clock3,Gift,Baby,CheckCircle2,Heart,ChevronRight,Users,ArrowLeft,Music2}from'lucide-react';
import'./style.css';

const API=(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'')+'/functions/v1/invite-api';
const amazon='https://www.amazon.com.br/baby-reg/gustavo-henrique-janeiro-2027-sopaulo/K6BQ3XFQQ9IO?ref_=cm_sw_r_cp_ud_dp_17SYTR1MP6FTCSNQMQHC';
async function api(payload){if(!import.meta.env.VITE_SUPABASE_URL)throw new Error('Supabase não configurado');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro');return d}
function App(){
 const[q,setQ]=useState(''),[matches,setMatches]=useState([]),[selected,setSelected]=useState(null),[step,setStep]=useState('search'),[pin,setPin]=useState('');
 const[people,setPeople]=useState([]),[giftMode,setGiftMode]=useState('family'),[submitted,setSubmitted]=useState(false),[diapers,setDiapers]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const t=setTimeout(async()=>{if(q.trim().length<2){setMatches([]);return}try{const d=await api({action:'search',q});setMatches(d.families||[])}catch(e){setError(e.message)}},250);return()=>clearTimeout(t)},[q]);
 const openFamily=f=>{setSelected(f);setPin('');setStep('pin');setSubmitted(false);setError('')};
 const unlock=async()=>{setBusy(true);setError('');try{const d=await api({action:'unlock',familyId:selected.family_id,pin});setSelected({...selected,...d.family});setPeople(d.guests.map(g=>({id:g.id,name:g.name,going:g.attendance==='yes',type:g.person_type==='adult'?'adult':g.child_age_group==='under_5'?'child-under5':g.person_type==='child'?'child5':'adult'})));setGiftMode(d.family.giftMode==='per_adult'?'adult':d.family.giftMode||'family');setDiapers(d.diapers.map(x=>x.diaper_size));setSubmitted(d.family.status!=='invited'&&d.family.status!=='waiting');setStep('rsvp')}catch{setError('Código incorreto. Confira o código enviado no convite.')}finally{setBusy(false)}};
 const attending=people.filter(p=>p.going).length,adults=people.filter(p=>p.going&&p.type==='adult').length,counted=people.filter(p=>p.going&&p.type!=='child-under5').length;
 const gifts=giftMode==='adult'?adults:giftMode==='family'&&attending?1:0;
 const submit=async()=>{setBusy(true);setError('');try{const d=await api({action:'save',familyId:selected.family_id,pin,guests:people,giftMode});setDiapers((d.diapers||[]).map(x=>x.diaper_size));setSubmitted(true)}catch(e){setError('Não foi possível salvar. Tente novamente.')}finally{setBusy(false)}};
 const reset=()=>{setStep('search');setSelected(null);setQ('');setSubmitted(false);setError('')};
 return <main>
 <header><b>Chá do Oliver</b><nav><a href="#inicio">Início</a><a href="#confirmar">Confirme sua presença</a><a href="#presente">Sugestão de presente</a><a href="#local">Local</a></nav></header>
 <section id="inicio" className="hero"><div className="heroArt"><img src="/ChatGPT Image Sep 16, 2026, 12_47_30 PM.png" alt="Banda de animais do Chá do Oliver"/></div><div className="heroCopy"><span>CHÁ DO</span><h1>Oliver</h1><p>PEQUENAS COISAS,<br/>GRANDES COMEÇOS</p></div></section>
 <section id="confirmar" className="rsvpShell"><div className="leaf">❦</div>{step==='search'&&<><h2>Vamos confirmar sua presença? <Heart/></h2><p>Digite seu nome para encontrarmos seu convite.<br/>Qualquer integrante da família pode fazer a confirmação por todos.</p><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Digite seu nome..."/></div>{matches.length>0&&<div className="suggestions">{matches.map(f=><button key={f.family_id} onClick={()=>openFamily(f)}><b>{f.matched_name}</b><span>Família {f.display_name}</span><ChevronRight/></button>)}</div>}<p className="hint">Digite pelo menos 2 letras para localizar seu núcleo familiar.</p></>}
 {step==='pin'&&<><button className="back" onClick={reset}><ArrowLeft/> Voltar</button><h2>Encontramos vocês! 💛</h2><p className="familyNames">{selected.display_name}</p><p>Este é seu núcleo familiar? Digite o código enviado junto ao convite para acessar.</p><div className="pinbox"><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" placeholder="••••"/><button onClick={unlock} disabled={pin.length!==4||busy}>{busy?'Abrindo...':'Acessar convite'}</button></div></>}
 {error&&<small className="error">{error}</small>}
 {step==='rsvp'&&<><button className="back" onClick={reset}><ArrowLeft/> Trocar família</button><h2>{submitted?'Seu convite 💛':'Quem estará com a gente?'}</h2><p className="familyNames">{selected.displayName||selected.display_name}</p>{submitted&&<div className="saved"><CheckCircle2/><b>Esta família já respondeu.</b><span>Você pode consultar a sugestão abaixo ou atualizar a confirmação.</span></div>}
 <div className="people">{people.map(p=><div className="person" key={p.id}><label><input type="checkbox" checked={p.going} onChange={e=>setPeople(people.map(x=>x.id===p.id?{...x,going:e.target.checked}:x))}/><b>{p.name}</b><span>{p.going?'Vai':'Não vai'}</span></label>{p.going&&<select value={p.type} onChange={e=>setPeople(people.map(x=>x.id===p.id?{...x,type:e.target.value}:x))}><option value="adult">Adulto</option><option value="child5">Criança — 5 anos ou mais</option><option value="child-under5">Criança — menor de 5 anos</option></select>}</div>)}</div>
 <div className="capacity"><Users/><div><b>{attending} {attending===1?'pessoa confirmada':'pessoas confirmadas'}</b><small>{counted} contabilizada(s) pelo espaço · crianças menores de 5 anos não entram no limite</small></div></div>
 {attending>0&&<div id="presente" className="giftChoice"><h3>Como vocês pretendem presentear o Oliver?</h3>{[['family','Levaremos um presente pela família'],['adult','Levaremos um presente por convidado adulto'],['unknown','Ainda não sabemos']].map(o=><label className="radio" key={o[0]}><input type="radio" name="gift" checked={giftMode===o[0]} onChange={()=>setGiftMode(o[0])}/><span>{o[1]}</span></label>)}</div>}
 <button className="primary wide" onClick={submit} disabled={busy}>{busy?'Salvando...':submitted?'Atualizar confirmação':attending?'Confirmar presença':'Informar que não iremos'}</button>
 {submitted&&<Result attending={attending} giftMode={giftMode} gifts={gifts} diapers={diapers}/>}</>}
 </section>
 <section className="features"><Info icon="👨‍👩‍👧" title="Confirmação fácil e rápida">Qualquer integrante da família pode responder por todos.</Info><Info icon="♡" title="Cada presença faz a diferença">Estamos preparando tudo com muito carinho para receber vocês!</Info><Info icon="🎁" title="Sugestão de presente">Fraldas P, M, G ou XG + um Presentinho para o Oliver.</Info><Info icon="☆" title="Consulte quando quiser">Volte ao site, encontre sua família e consulte novamente sua sugestão.</Info></section>
 <section id="local" className="eventPanel"><div><CalendarDays/><b>DATA</b><strong>04/DEZEMBRO</strong><span>(sexta-feira)</span></div><div><Clock3/><b>HORÁRIO</b><strong>A partir das 18h</strong></div><div><MapPin/><b>LOCAL</b><strong>Salão Terra Mágina</strong><span>Av. das Nações, 151 - sobreloja<br/>Parque Novo Oratório<br/>Santo André - SP, 09260-000</span></div></section>
 <section className="closing"><Heart/><h2>Será um dia muito especial!</h2><p>Estamos muito felizes em compartilhar esse momento com você.</p></section><footer><Music2/> CHÁ DO OLIVER · COM MUITO AMOR ♥</footer></main>
}
function Result({attending,giftMode,gifts,diapers}){if(!attending)return <div className="result"><Heart/><h3>Vamos sentir sua falta!</h3><p>Obrigado por nos avisar. Caso queira presentear o Oliver mesmo à distância, preparamos uma lista online.</p><a className="primary" href={amazon} target="_blank" rel="noreferrer">Ver lista na Amazon</a></div>;return <div className="result"><CheckCircle2/><h3>Presença confirmada 💛</h3>{giftMode==='unknown'?<p>Quando quiser, você pode voltar ao site e atualizar como pretende presentear o Oliver.</p>:<><p>{gifts===1?'Esta é a sugestão da família:':'Estas são as sugestões para vocês:'}</p>{diapers.slice(0,gifts).map((d,i)=><div className="gift" key={i}><Baby/><div><small>Sugestão {gifts>1?i+1:''}</small><b>1 pacote de fraldas — tamanho {d}</b></div><Gift/><div><b>Presentinho para o Oliver</b><span>Roupinha, item de higiene, acessório ou qualquer mimo que você sentir vontade de levar.</span></div></div>)}</>}</div>}
function Info({icon,title,children}){return <div><i>{icon}</i><h3>{title}</h3><p>{children}</p></div>}
createRoot(document.getElementById('root')).render(<App/>);