import React,{useState,useEffect} from 'react';
import{createRoot}from'react-dom/client';
import{Search,MapPin,CalendarDays,Clock3,Gift,Baby,CheckCircle2,Heart,ChevronRight,Users,ArrowLeft,Music2,ExternalLink}from'lucide-react';
import'./style.css';
const API=(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'')+'/functions/v1/invite-api';
const amazon='https://www.amazon.com.br/baby-reg/gustavo-henrique-janeiro-2027-sopaulo/K6BQ3XFQQ9IO?ref_=cm_sw_r_cp_ud_dp_17SYTR1MP6FTCSNQMQHC';
const hero='/images/banner-oliver.png';
const eventTitle='Chá do Oliver';
const eventLocation='Salão Terra Mágica - Av. das Nações, 151 - sobreloja - Parque Novo Oratório, Santo André - SP, 09260-000';
const googleCalendar='https://calendar.google.com/calendar/render?action=TEMPLATE&text='+encodeURIComponent(eventTitle)+'&dates=20261204T210000Z/20261205T010000Z&details='+encodeURIComponent('Chá do Oliver 💛 Esperamos você para celebrar conosco!')+'&location='+encodeURIComponent(eventLocation);
function downloadCalendar(){
 const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Cha do Oliver//Convite//PT-BR','BEGIN:VEVENT','UID:cha-do-oliver-20261204@convite','DTSTAMP:20260916T220000Z','DTSTART:20261204T210000Z','DTEND:20261205T010000Z','SUMMARY:Chá do Oliver','LOCATION:'+eventLocation.replace(/,/g,'\\,'),'DESCRIPTION:Chá do Oliver - esperamos você para celebrar conosco!','END:VEVENT','END:VCALENDAR'].join('\\r\\n');
 const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cha-do-oliver.ics';a.click();URL.revokeObjectURL(url);
}
async function api(payload){if(!import.meta.env.VITE_SUPABASE_URL)throw new Error('Supabase não configurado');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erro');return d}
function App(){
 const[q,setQ]=useState(''),[matches,setMatches]=useState([]),[selected,setSelected]=useState(null),[step,setStep]=useState('search'),[pin,setPin]=useState('');
 const[people,setPeople]=useState([]),[giftMode,setGiftMode]=useState('family'),[submitted,setSubmitted]=useState(false),[diapers,setDiapers]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const t=setTimeout(async()=>{setError('');if(q.trim().length<2){setMatches([]);return}try{const d=await api({action:'search',q});setMatches(d.families||[])}catch(e){setError(e.message)}},250);return()=>clearTimeout(t)},[q]);
 const openFamily=f=>{setSelected(f);setPin('');setStep('pin');setSubmitted(false);setError('');window.scrollTo({top:document.getElementById('confirmar')?.offsetTop-70,behavior:'smooth'})};
 const unlock=async()=>{setBusy(true);setError('');try{const d=await api({action:'unlock',familyId:selected.family_id,pin});setSelected({...selected,...d.family});setPeople(d.guests.map(g=>({id:g.id,name:g.name,going:g.attendance==='yes',type:g.person_type==='adult'?'adult':g.child_age_group==='under_5'?'child-under5':g.person_type==='child'?'child5':'adult'})));setGiftMode(d.family.giftMode==='per_adult'?'adult':d.family.giftMode||'family');setDiapers(d.diapers.map(x=>x.diaper_size));setSubmitted(d.family.status!=='invited'&&d.family.status!=='waiting');setStep('rsvp')}catch{setError('Código incorreto. Confira o código enviado no convite.')}finally{setBusy(false)}};
 const attending=people.filter(p=>p.going).length,adults=people.filter(p=>p.going&&p.type==='adult').length,counted=people.filter(p=>p.going&&p.type!=='child-under5').length;
 const gifts=giftMode==='adult'?adults:giftMode==='family'&&attending?1:0;
 const submit=async()=>{setBusy(true);setError('');try{const d=await api({action:'save',familyId:selected.family_id,pin,guests:people,giftMode});setDiapers((d.diapers||[]).map(x=>x.diaper_size));setSubmitted(true);setTimeout(()=>document.querySelector('.result')?.scrollIntoView({behavior:'smooth',block:'center'}),50)}catch{setError('Não foi possível salvar. Tente novamente.')}finally{setBusy(false)}};
 const reset=()=>{setStep('search');setSelected(null);setQ('');setMatches([]);setSubmitted(false);setError('')};
 return <main><header><a className="brand" href="#inicio">Chá do Oliver</a><nav><a href="#inicio">Início</a><a href="#confirmar">Confirmar</a><a href="#presente">Presentes</a><a href="#local">Local</a><a className="adminNav" href="/#painel">Painel</a></nav></header>
 <section id="inicio" className="hero" style={{backgroundImage:`url(${hero})`}}><div className="heroShade"/><div className="heroCopy"><small>SAVE THE DATE</small><span>Chá do</span><h1>Oliver</h1><p>Traga o amor, o sorriso e a fralda:<br/>estamos em contagem regressiva</p><a href="#confirmar">Confirmar presença <ChevronRight/></a></div></section>
 <section className="quick"><div><CalendarDays/><span><small>DATA</small><b>04/Dezembro</b><em className="dateDay">sexta-feira</em></span></div><div><Clock3/><span><small>HORÁRIO</small><b>A partir das 18h</b></span></div><div><MapPin/><span><small>LOCAL</small><b>Salão Terra Mágica</b></span></div></section>
 <section id="confirmar" className="rsvpShell"><div className="leaf">❦</div>{step==='search'&&<><span className="eyebrow">SEU CONVITE</span><h2>Vamos confirmar sua presença? <Heart/></h2><p>Digite seu nome para encontrarmos seu convite.<br/>Qualquer integrante da família pode responder por todos.</p><div className="searchbox"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Comece a digitar seu nome..." autoComplete="off"/></div>{matches.length>0&&<div className="suggestions">{matches.map(f=><button key={f.family_id} onClick={()=>openFamily(f)}><b>{f.matched_name}</b><span>Família {f.display_name}</span><ChevronRight/></button>)}</div>}<p className="hint">{q.length<2?'Digite pelo menos 2 letras.':matches.length===0&&!error?'Buscando seu convite...':'Selecione seu nome para continuar.'}</p></>}
 {step==='pin'&&<><button className="back" onClick={reset}><ArrowLeft/> Voltar</button><span className="eyebrow">NÚCLEO FAMILIAR</span><h2>Encontramos vocês! 💛</h2><p className="familyNames">{selected.display_name}</p><p>Digite o código de 4 números enviado junto ao convite.</p><div className="pinbox"><input value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,4))} inputMode="numeric" placeholder="••••" autoFocus/><button onClick={unlock} disabled={pin.length!==4||busy}>{busy?'Abrindo...':'Acessar convite'}</button></div></>}
 {error&&<div className="error">{error}</div>}
 {step==='rsvp'&&<><button className="back" onClick={reset}><ArrowLeft/> Trocar família</button><span className="eyebrow">CONFIRMAÇÃO</span><h2>{submitted?'Seu convite 💛':'Quem estará com a gente?'}</h2><p className="familyNames">{selected.displayName||selected.display_name}</p>{submitted&&<div className="saved"><CheckCircle2/><div><b>Confirmação salva</b><span>Você pode consultar o presente ou alterar as respostas abaixo.</span></div></div>}
 <div className="people">{people.map(p=><div className={'person '+(p.going?'going':'')} key={p.id}><label><input type="checkbox" checked={p.going} onChange={e=>setPeople(people.map(x=>x.id===p.id?{...x,going:e.target.checked}:x))}/><span className="check"/><span className="personName"><b>{p.name}</b><small>{p.going?'Presença confirmada':'Não irá'}</small></span></label>{p.going&&<select value={p.type} onChange={e=>setPeople(people.map(x=>x.id===p.id?{...x,type:e.target.value}:x))}><option value="adult">Adulto</option><option value="child5">Criança · 5 anos ou mais</option><option value="child-under5">Criança · menor de 5 anos</option></select>}</div>)}</div>
 <div className="capacity"><Users/><div><b>{attending} {attending===1?'presença':'presenças'} selecionada{attending===1?'':'s'}</b><small>{counted} contabilizada(s) pelo espaço. Crianças menores de 5 anos não entram no limite.</small></div></div>
 {attending>0&&<div id="presente" className="giftChoice"><span className="eyebrow">PRESENTE</span><h3>Como vocês pretendem presentear o Oliver?</h3><p>Além da fralda sugerida, o presentinho pode ser uma roupinha, item de higiene, acessório ou outro mimo.</p>{[['family','Um presente pela família'],['adult','Um presente por convidado adulto'],['unknown','Ainda não sabemos']].map(o=><label className="radio" key={o[0]}><input type="radio" name="gift" checked={giftMode===o[0]} onChange={()=>setGiftMode(o[0])}/><span>{o[1]}</span></label>)}</div>}
 <button className="primary wide" onClick={submit} disabled={busy}>{busy?'Salvando...':submitted?'Salvar alterações':attending?'Confirmar presença':'Informar que não iremos'}</button>{submitted&&<Result attending={attending} giftMode={giftMode} gifts={gifts} diapers={diapers}/>}</>}
 </section>
 <section className="features"><Info icon="👨‍👩‍👧" title="Uma resposta por família">Qualquer integrante pode confirmar a presença do núcleo.</Info><Info icon="♡" title="Feito com carinho">Estamos preparando cada detalhe para receber vocês.</Info><Info icon="🎁" title="Presente para o Oliver">Fralda sugerida + um presentinho escolhido por você.</Info><Info icon="☆" title="Consulte depois">Volte quando quiser para rever ou atualizar seu convite.</Info></section>
 <section id="local" className="eventPanel"><div><CalendarDays/><b>DATA</b><strong>04/Dezembro</strong><span>sexta-feira</span></div><div><Clock3/><b>HORÁRIO</b><strong>A partir das 18h</strong></div><div><MapPin/><b>LOCAL</b><strong>Salão Terra Mágica</strong><span>Av. das Nações, 151 - sobreloja<br/>Parque Novo Oratório · Santo André - SP<br/>09260-000</span><a href="https://www.google.com/maps/search/?api=1&query=Av.%20das%20Na%C3%A7%C3%B5es%2C%20151%2C%20Santo%20Andr%C3%A9%20SP" target="_blank" rel="noreferrer">Ver no mapa <ExternalLink/></a></div></section>
 <section className="closing"><Heart/><h2>Será um dia muito especial!</h2><p>O Oliver já é muito amado e mal podemos esperar para compartilhar esse momento com vocês.</p></section><footer><Music2/> CHÁ DO OLIVER · COM MUITO AMOR ♥</footer></main>
}
function Result({attending,giftMode,gifts,diapers}){if(!attending)return <div className="result"><Heart/><h3>Vamos sentir sua falta!</h3><p>Obrigado por nos avisar. Se quiser presentear o Oliver mesmo à distância, preparamos uma lista online.</p><a className="primary linkbtn" href={amazon} target="_blank" rel="noreferrer">Ver lista na Amazon <ExternalLink/></a></div>;return <div className="result"><CheckCircle2/><h3>Presença confirmada 💛</h3>{giftMode==='unknown'?<p>Quando quiser, volte ao site para consultar ou atualizar sua escolha.</p>:<><p>{gifts===1?'Esta é a sugestão da família:':'Estas são as sugestões para vocês:'}</p>{diapers.slice(0,gifts).map((d,i)=><div className="gift" key={i}><div className="giftIcon"><Baby/></div><div><small>{gifts>1?'SUGESTÃO '+(i+1):'SUGESTÃO DA FAMÍLIA'}</small><b>1 pacote de fraldas · tamanho {d}</b></div><div className="giftIcon"><Gift/></div><div><b>Presentinho para o Oliver</b><span>Roupinha, item de higiene, acessório ou qualquer mimo que você sentir vontade de levar.</span></div></div>)}</>}<div className="calendarPanel"><CalendarDays/><div><span className="eyebrow">NÃO ESQUEÇA A DATA</span><h3>Adicione o Chá do Oliver à sua agenda</h3><p>04 de dezembro · das 18h às 22h</p><div className="calendarActions"><a className="primary linkbtn" href={googleCalendar} target="_blank" rel="noreferrer">Adicionar ao Google Agenda <ExternalLink/></a><button className="calendarIcs" onClick={downloadCalendar}>Apple, Outlook e outros calendários</button></div></div></div></div>}
function Info({icon,title,children}){return <div><i>{icon}</i><h3>{title}</h3><p>{children}</p></div>}

function AdminPanel(){
 const[code,setCode]=useState(sessionStorage.getItem('oliverAdmin')||''),[families,setFamilies]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[filter,setFilter]=useState('');
 const load=async(adminCode=code)=>{setLoading(true);setError('');try{const d=await api({action:'adminList',adminCode});setFamilies(d.families||[]);sessionStorage.setItem('oliverAdmin',adminCode)}catch(e){setError('Código administrativo inválido ou não foi possível carregar o painel.')}finally{setLoading(false)}};
 useEffect(()=>{if(code&&sessionStorage.getItem('oliverAdmin'))load(code)},[]);
 const makePin=async(f)=>{if(f.invite_pin_plain&&!window.confirm('Este núcleo já possui um token visível. Deseja substituí-lo?'))return;const pin=String(Math.floor(1000+Math.random()*9000));try{await api({action:'adminSetPin',adminCode:code,familyId:f.id,pin});setFamilies(families.map(x=>x.id===f.id?{...x,invite_pin_plain:pin}:x))}catch{setError('Não foi possível gerar o token.')}};
 const message=f=>`Olá, ${f.display_name}! 💛

Estamos preparando com muito carinho o Chá do Oliver e queremos celebrar esse momento com vocês.

Acesse o convite:
${window.location.origin}

Para confirmar a presença, procure pelo nome de um dos integrantes da família e utilize o código de acesso:
${f.invite_pin_plain||'[gere o token no painel]'}

📅 04 de dezembro (sexta-feira)
🕕 Das 18h às 22h
📍 Salão Terra Mágica

Traga o amor, o sorriso e a fralda: estamos em contagem regressiva! 💛`;
 const copy=async f=>{await navigator.clipboard.writeText(message(f));alert('Texto do convite copiado!')};
 const shown=families.filter(f=>(f.display_name+' '+(f.group_name||'')+' '+(f.guests||[]).map(g=>g.name).join(' ')).toLowerCase().includes(filter.toLowerCase()));
 const totalGuests=families.reduce((n,f)=>n+(f.guests?.length||0),0),confirmed=families.reduce((n,f)=>n+(f.guests||[]).filter(g=>g.attendance==='yes').length,0);
 if(!families.length)return <main className="adminPage"><section className="adminLogin"><span className="eyebrow">CHÁ DO OLIVER</span><h1>Painel de convidados</h1><p>Digite o código administrativo para acessar a lista.</p><input type="password" inputMode="numeric" value={code} onChange={e=>setCode(e.target.value)} placeholder="Código administrativo"/><button className="primary" onClick={()=>load()} disabled={loading}>{loading?'Carregando...':'Entrar no painel'}</button>{error&&<div className="error">{error}</div>}</section></main>;
 return <main className="adminPage"><header><a className="brand" href="/">Chá do Oliver</a><nav><a href="/">Ver convite</a></nav></header><section className="adminWrap"><div className="adminHeading"><div><span className="eyebrow">ADMINISTRAÇÃO</span><h1>Lista de convidados</h1><p>Organize os núcleos e copie o convite com link e token.</p></div><button onClick={()=>{sessionStorage.removeItem('oliverAdmin');setFamilies([]);setCode('')}}>Sair</button></div>
 <div className="adminStats"><div><b>{families.length}</b><span>Núcleos</span></div><div><b>{totalGuests}</b><span>Convidados</span></div><div><b>{confirmed}</b><span>Confirmados</span></div><div><b>{totalGuests-confirmed}</b><span>Demais convidados</span></div></div>
 <div className="adminTools"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Buscar convidado ou família..."/><span>{shown.length} núcleo(s)</span></div>
 <div className="guestList">{shown.map(f=><article className="guestRow" key={f.id}><div className="guestNumber">#{String(f.number).padStart(3,'0')}</div><div className="guestMain"><div className="guestTitle"><h3>{f.display_name}</h3><span className={'status '+f.invite_status}>{f.invite_status}</span></div><p>{(f.guests||[]).map(g=>g.name).join(' · ')}</p><div className="guestMeta"><span>{f.guests?.length||0} convidado(s)</span><span>{(f.guests||[]).filter(g=>g.attendance==='yes').length} confirmado(s)</span><span>Token: <b>{f.invite_pin_plain||'não disponível'}</b></span></div></div><div className="guestActions"><button onClick={()=>makePin(f)}>{f.invite_pin_plain?'Trocar token':'Gerar token'}</button><button className="primary" onClick={()=>copy(f)} disabled={!f.invite_pin_plain}>Copiar convite</button></div></article>)}</div>
 {error&&<div className="error">{error}</div>}</section></main>
}
const isAdmin=window.location.hash==='#painel'||window.location.pathname==='/painel';
createRoot(document.getElementById('root')).render(isAdmin?<AdminPanel/>:<App/>);